### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#1]
Currently the versioning of `solc` is not 100% [semver](http://semver.org/) (and thus npm) compatible.

e.g. `0.3.1-1` translates to _prerelease version_ of 1.

For reference, the C solc has a version of `v0.3.2-2016-04-22-dd4300d`, which includes a lot of build metadata. The right way to include that is by using the plus sign: `0.3.1+1` or `0.3.1+2016-04-22-dd4300d`.

@chriseth also raised that mirroring the version in JS causes the issue that interface changes in JS cannot be properly signaled using semver as it is tied to the C version.

**Comment by chriseth** [comment]
This requires a change to `downloadCurrentVersion.js` - so not doing that for 0.3.5

**Comment by chriseth** [comment]
We should change packages.json to include exactly the version returned by the `version()` function of the compiler.

**Comment by axic** [comment]
> We should change packages.json to include exactly the version returned by the version() function of the compiler.

Not sure that's canonically possible, `npm version` will bump both the file and do git tagging. We have to replicate both in a script.

**Comment by axic** [comment]
@chriseth What we could do is add a check to prepublish which aborts if the versions don't match.
