### ISSUE TITLE
Clarify error reporting in solcjs (stderr/stdout/solidity warnings vs. errors)

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#104]
Right now in `solcjs` we have different outputs:
- Commandline validation errors are on stderr
- Node.js errors (e.g. file reading error) is on stderr
- Warnings & Errors from the Solidity compiler is on stdout
- In `---standard-json` mode the exit value reflects what happened
- Otherwise it is always successful

I think we should go for:
- all errors on stderr
- 'Error' from Solidity is on stderr
- 'Warning' from Solidity is on stdout
- exit(1) if stderr is not empty
- exit(0) otherwise

**Comment by chriseth** [comment]
If the json is on stdout, warnings should go to stderr.
