### ISSUE TITLE
solcjs doesn't appear to do anything on Windows

### ISSUE THREAD

**Issue by ripper234** [ethereum/solc-js#109]
Either I'm doing something wrong (the usage instructions are unclear), or there's a bug:

I just installed latest solcjs `npm install -g solcjs` on my Windows 10 machine, trying to compile a simple script.

Running 

```solcjs --bin Coin.sol``` thinks for a bit, and doesn't actually do anything, where Coin.sol is the following file:

```
pragma solidity ^0.4.0;

contract Coin {
    // The keyword "public" makes those variables
    // readable from outside.
    address public minter;
    mapping (address => uint) public balances;

    // Events allow light clients to react on
    // changes efficiently.
    event Sent(address from, address to, uint amount);

    // This is the constructor whose code is
    // run only when the contract is created.
    function Coin() {
        minter = msg.sender;
    }

    function mint(address receiver, uint amount) {
        if (msg.sender != minter) return;
        balances[receiver] += amount;
    }

    function send(address receiver, uint amount) {
        if (balances[msg.sender] < amount) return;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        Sent(msg.sender, receiver, amount);
    }
}
```

solcjs version is ```0.4.11+commit.68ef5810.Emscripten.clang```

**Comment by axic** [comment]
Do you have any output on the screen or any shell exit code?

**Comment by ripper234** [comment]
The exit code is 0, no output.

```
C:\tmp>solcjs --bin Coin.sol

C:\tmp>echo %ERRORLEVEL%
0
```

**Comment by axic** [comment]
Sorry, `solcjs` actually writes a file and doesn't show anything on screen. You should have a file `Coin.sol:Coin.bin`.

**Comment by chriseth** [comment]
... which might be impossible on windows - `:` might be invalid in filenames for windows.

**Comment by ripper234** [comment]
I believe it is indeed an invalid filename.
It is odd that an error isn't detected though.
