### ISSUE TITLE
Generate ABI only

### ISSUE THREAD

**Issue by ruchevits** [ethereum/solc-js#112]
Is it possible to generate ABI only, w/o compiling contract to bytecode?

**Comment by chriseth** [comment]
Yes, this is a planned feature.

**Comment by axic** [comment]
@ruchevits you can start using the new JSON mode (with `solc.compileStandardWrapper`, see http://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description for more information). In future versions the compiler will honour the `outputSelection` field.

**Comment by axic** [comment]
The `outputSelection` feature will be enabled by https://github.com/ethereum/solidity/pull/2146.
