### ISSUE TITLE
Solidity syntax errors produce an unexpected `abort` and print two 5's to the console

### ISSUE THREAD

**Issue by tcoulter** [ethereum/solc-js#113]
If the code sent to solc-js contains a syntax error, solc-js will throw an error with the message `abort(5)`. It also prints two 5's to the console. This affects the Truffle stack as all users who accidentally produce syntax errors won't be able to diagnose the issue.

I've written a sample script that reproduces the error:

```javascript
#!/usr/bin/env node
var solc = require("solc");

var solcStandardInput = {
  language: "Solidity",
  sources: {
    "Contract.sol": {content: "pragma solidity ^0.4.11; contract Contract { this is a syntax error }"}
  },
  settings: {
    optimizer: {
      enabled: true,
      runs: 0 // See https://github.com/ethereum/solidity/issues/2245
    },
  }
};

// This error's and prints out two 5's
solc.compileStandardWrapper(JSON.stringify(solcStandardInput));
```

The output you get looks like this:

<img width="1438" alt="screen shot 2017-06-27 at 10 33 36 am" src="https://user-images.githubusercontent.com/92629/27601404-218d8158-5b24-11e7-958f-9b1453076cb3.png">

**Comment by axic** [comment]
It probably is some kind of Emscripten specific json error, because compiling the same input via the commandline works:
```
$ solc/solc --standard-json < _113.json 
{"errors":[{"component":"general","formattedMessage":"Internal exception in StandardCompiler::compileInternal: /Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(508): Throw in function const dev::solidity::SourceUnit &dev::solidity::CompilerStack::ast(const string &) const\nDynamic exception type: boost::exception_detail::clone_impl<dev::solidity::CompilerError>\nstd::exception::what: std::exception\n[dev::tag_comment*] = Parsing was not successful.\n","message":"Internal exception in StandardCompiler::compileInternal: /Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(508): Throw in function const dev::solidity::SourceUnit &dev::solidity::CompilerStack::ast(const string &) const\nDynamic exception type: boost::exception_detail::clone_impl<dev::solidity::CompilerError>\nstd::exception::what: std::exception\n[dev::tag_comment*] = Parsing was not successful.\n","severity":"error","type":"InternalCompilerError"}]}
```

**Comment by axic** [comment]
The two fives are printed at:

https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/postamble.js#L285

because `abort(5)` is called and 5 is the *message*.

**Comment by axic** [comment]
We could enable debugging/safety features in the emscripten build (https://kripken.github.io/emscripten-site/docs/porting/Debugging.html):
- `ASSERTIONS=1` is used to enable runtime checks for common memory allocation errors
- `SAFE_HEAP=1` adds additional memory access checks, and will give clear errors for problems like dereferencing 0 and memory alignment issues.
- `STACK_OVERFLOW_CHECK=1` (see the description there)

**Comment by axic** [comment]
A test needs to be added to both `compile` and `compileStandard` to ensure they are handled correctly.

**Comment by axic** [comment]
@tcoulter did version 0.4.13 fix this?

**Comment by axic** [comment]
It definitely works with 0.4.13:

```
$ ./solcjs --version
0.4.13+commit.0fb4cb1a.Emscripten.clang
$ ./solcjs --standard-json <_113.json 
{"contracts":{},"errors":[{"component":"general","formattedMessage":"Contract.sol:1:51: ParserError: Expected identifier, got 'Is'\npragma solidity ^0.4.11; contract Contract { this is a syntax error }\n                                                  ^\n","message":"Expected identifier, got 'Is'","severity":"error","type":"ParserError"}],"sources":{}}
```

**Comment by JohnAllen** [comment]
This can happen when you declare `struct` members `public`: 

```
struct Restaurant { bool public open; }
```
