### ISSUE TITLE
Support imports in solcjs CLI

### ISSUE THREAD

**Issue by lukehedger** [ethereum/solc-js#114]
Given the following directory structure:
```
contracts/
  Source.sol
  Imported.sol
```

Where `Source.sol`:
```
pragma solidity ^0.4.0;

import './Imported.sol';

contract Source {
}
```

Running the following command:
```
solcjs --optimize --bin contracts/Source.sol
```

Based on [the docs](http://solidity.readthedocs.io/en/develop/layout-of-source-files.html#paths), I would expect the compiler to resolve the import but instead it throws:
```
contracts/Source.sol:3:1: Error: Source "contracts/Imported.sol" not found: File not supplied initially.
import './Imported.sol';
^---------------------^
```

If I include `Imported.sol` as a source file it will compile without error:
```
solcjs --optimize --bin contracts/Source.sol contracts/Imported.sol
```

Could you clarify my understanding here or is this a bug? Thanks! 🙃

**Comment by lukehedger** [comment]
Just seen this note in readme:
> Note that all input files that are imported have to be supplied, the compiler will not load any additional files on its own.

Which answers my question!

What's the reason for this/any scope for improving it in the future?

**Comment by axic** [comment]
@lukehedger someone needs to do implement it. If you are interested adding support for it, please make a PR and we're happy to help to finish and include that feature.

**Comment by lukehedger** [comment]
Happy to look at adding support but would you be able to point me in the right direction to get started? Would the feature be added to the JS bindings or to the compiler itself?

**Comment by axic** [comment]
This is a feature missing in the `solcjs` tool included in this repository. The `solc.compile` method supports a callback to read external files, see https://github.com/ethereum/solc-js#from-version-021

**Comment by lukehedger** [comment]
Just came across this tool which may be of use in the meantime: https://github.com/TiesNetwork/solidify

**Comment by mimitc123** [comment]
how to use https://github.com/TiesNetwork/solidify

**Comment by Suhail** [comment]
I solved this by doing as things have been improved as of 0.4.x:

var solc = require('solc');
var fs = require('fs');

var inputs = {
    'auction.sol': fs.readFileSync('auction.sol').toString(),
};

function findImports(path) {
    return {
        'contents': fs.readFileSync(path).toString()
    }
}

var compiledCode = solc.compile({sources: inputs}, 1, findImports)

fs.writeFile('compiled.json', JSON.stringify(compiledCode), function(err) {
    if (err) throw err;
    console.log('Compiled & saved');
});

**Comment by arashkiani** [comment]
so writing import is just a fun activity that solc dont understand ?

**Comment by aj0strow** [comment]
It looks like if `findImports(path)` had a second parameter, the source file that is calling import, it would be easy to generalize this.

```js
var fs = require('fs')
var path = require('path')

function findImports(importPath, sourcePath) {
  try {
    var filePath = path.resolve(sourcePath, importPath)
    return { contents: fs.readFileSync(filePath).toString() }
  } catch (e) {
    return { error: e.message }
  }
}

solc.compile(..., findImports)
```

Is there a way to receive the source path too? I tried looking in the `soljson.js` file but it looks like it is already compiled from somewhere else.

**Comment by kangdao** [comment]
solcjs --abi contract.sol
Tell me how to generate bytecode

**Comment by wangjj9219** [comment]
@kangdao try it： solcjs --bin contract.sol

**Comment by uluhonolulu** [comment]
@axic I tried to include all imported contracts, but it still fails for me (Windows, version `0.5.4+commit.9549d8ff.Emscripten.clang`):
```
> solcjs .\contracts\StorageController.sol .\contracts\Owned.sol .\contracts\SafeMath.sol .\contracts\Owned.sol --bin
.\contracts\StorageController.sol:4:1: ParserError: Source "BaseContract.sol" not found: File import callback not supported
import "./BaseContract.sol";
^--------------------------^

.\contracts\StorageController.sol:5:1: ParserError: Source "Owned.sol" not found: File import callback not supported
import "./Owned.sol";
^-------------------^

.\contracts\StorageController.sol:6:1: ParserError: Source "SafeMath.sol" not found: File import callback not supported
import "./SafeMath.sol";
```

**Comment by axic** [comment]
The feature is not implemented yet. Passing multiple contracts will work unfortunately.

**Comment by fasidOnGit** [comment]
**Bingo! I have a fix that works!!  This will simply compile all the `.sol` files and feed it into `solc.compile`**

```
//uitls.js

const fs = require('fs');
const path = require('path');
const findImports = (dir) => {
    const files = walkSync(dir);
    return (fileName) => {
        const fileNames = Object.keys(files);
        for(const key in files) {
            if(key.indexOf(fileName) > -1) {
                return { contents: files[key]};
            }
        }
        return {error: fileName + 'not Found'};
    }
};

const walkSync = (dir, filelist) => {
    var fs = fs || require('fs'),
        files = fs.readdirSync(dir);
    filelist = filelist || [];
    files.forEach(function(file) {
        if (fs.statSync(dir + '/' + file).isDirectory()) {
            console.log('Directory:', dir + '/' + file);
            filelist = walkSync(dir + '/' + file, filelist);
        }
        else {
            if(file.indexOf('.sol') > 0) {
                console.log('File: ', dir + '/' + file)
                // filelist.push({[file]: fs.readFileSync(dir + '/' + file, 'utf-8')});
                filelist[dir + '/' + file] = fs.readFileSync(dir + '/' + file, 'utf-8')
            }
        }
    });
    return filelist;
};

module.exports = {
    findImports
};
```

and in solc.compile just pass this as the last parameter like so
```
//compile.js
const {findImports} = require('utils.js');
...
const input = YOUR_INPUT_JSON_TO_COMPILE;
solc.compile(JSON.stringify(input), findImports(__dirname + '/contracts'));
...
...
```

**Comment by akiabi** [comment]
> **Bingo! I have a fix that works!! This will simply compile all the `.sol` files in the directory and its sub-directories and feed it into `solc.compile`**
> 
> ```
> //uitls.js
> 
> const fs = require('fs');
> const path = require('path');
> const findImports = (dir) => {
>     const files = walkSync(dir);
>     return (fileName) => {
>         const fileNames = Object.keys(files);
>         for(const key in files) {
>             if(key.indexOf(fileName) > -1) {
>                 return { contents: files[key]};
>             }
>         }
>         return {error: fileName + 'not Found'};
>     }
> };
> 
> const walkSync = (dir, filelist) => {
>     var fs = fs || require('fs'),
>         files = fs.readdirSync(dir);
>     filelist = filelist || [];
>     files.forEach(function(file) {
>         if (fs.statSync(dir + '/' + file).isDirectory()) {
>             console.log('Directory:', dir + '/' + file);
>             filelist = walkSync(dir + '/' + file, filelist);
>         }
>         else {
>             if(file.indexOf('.sol') > 0) {
>                 console.log('File: ', dir + '/' + file)
>                 // filelist.push({[file]: fs.readFileSync(dir + '/' + file, 'utf-8')});
>                 filelist[dir + '/' + file] = fs.readFileSync(dir + '/' + file, 'utf-8')
>             }
>         }
>     });
>     return filelist;
> };
> 
> module.exports = {
>     findImports
> };
> ```
> 
> and in solc.compile just pass this as the last parameter like so
> 
> ```
> //compile.js
> const {findImports} = require('./utils');
> ...
> const input = YOUR_INPUT_JSON_TO_COMPILE;
> solc.compile(JSON.stringify(input), findImports(__dirname + '/contracts'));
> ...
> ...
> ```

wer shld be the utilis.js and  compile.js shld be added?

**Comment by fasidOnGit** [comment]
@akiabi Could be at the project root dir?

**Comment by Garito** [comment]
Hi
I use the remappings option in settings to do this
Why is here different or am I losing something?

**Comment by bakeiro** [comment]
Hi!

I'm getting a `Invalid callback object specified` all the time, seems that the second parameter needs to be an object and not a callback (solc 8.10)

does anyone knows more about this? thanks!

**Comment by chriseth** [comment]
Can you come to the solidity gitter / matrix channel as described in the readme: https://github.com/ethereum/solidity#readme ?

**Comment by jonathansmirnoff** [comment]
> Hi!
> 
> I'm getting a `Invalid callback object specified` all the time, seems that the second parameter needs to be an object and not a callback (solc 8.10)
> 
> does anyone knows more about this? thanks!
> 
> ![image](https://user-images.githubusercontent.com/16777161/146006177-a5808ab1-7164-40f0-ba9b-9cd02761466f.png)

did you find a way to solve this?
