### ISSUE TITLE
Rework the API in a breaking release

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#120]
Currently there is:
- `compile` which wraps `compileJSON`, `compileJSONMulti` and `compileJSONCallback`
- `compileStandard` which wraps `compileStandard`
- `compileStandardWrapper` which uses or emulates `compileStandard`

I think the only method should be:
- `compile` which provide the standard JSON interface (uses `compileStandard` or emulates it`)

**Comment by axic** [comment]
What is left: change `solcjs` to always use Standard JSON.

**Comment by Tectract** [comment]
This caused a breaking change in browser-solc, and I'm trying to figure out how to fix it...

https://github.com/ericxtang/browser-solc/issues/4

RuntimeError: abort(Assertion failed: Cannot call unknown function compileJSON, make sure it is exported). Build with -s ASSERTIONS=1 for more info.

argh, compiler.compiler no longer works
