### ISSUE TITLE
Browserify - Uncaught TypeError: soljson.cwrap is not a function

### ISSUE THREAD

**Issue by Janaka-Steph** [ethereum/solc-js#125]
Hello,

I use browserify in order to use solc in the browser.
I have the most simple setup and run the most simple command `browserify index.js -o bundle.js`.

I have this error:
```
Uncaught TypeError: soljson.cwrap is not a function
    at setupMethods (bundle.js:9753)
    at Object.39../soljson.js (bundle.js:9599)
    at s (bundle.js:1)
    at bundle.js:1
    at Object.1.solc (bundle.js:3)
    at s (bundle.js:1)
    at e (bundle.js:1)
    at bundle.js:1
```

**Comment by axic** [comment]
It is very likely not possible, but at least not practical, to browserify `index.js`, because that will load an Emscripten compiled Solidity of around 10Mb size. Instead, browserifiy `wrapper.js`, load a Solidity compiler (ones found in the `solc-bin` repo) and pass it to the wrapper.

**Comment by Janaka-Steph** [comment]
A little doc about it would be nice

**Comment by axic** [comment]
I was able to browserify it with the above command though, are you sure you have tun `npm run downloadsolc` before browserifying?

**Comment by axic** [comment]
Can we migrate the discussion to #31?
