### ISSUE TITLE
compiled bytecode can't valid on etherscan

### ISSUE THREAD

**Issue by 362228416** [ethereum/solc-js#137]
Solc compiled bytecode inconsistent results with https://etherscan.io/verifyContract2 compiled,my  compiler version is consistent, also enabled the compression, contract no parameters, the compiled bytecode behind dozens of inconsistencies, front is the same, tried many times, is always the same, I don't know why

**Comment by axic** [comment]
Can you please open a more comprehensive report on https://github.com/ethereum/solidity ? Please include contract source and address.
