### ISSUE TITLE
Crash in RedHat...

### ISSUE THREAD

**Issue by born2net** [ethereum/solc-js#138]
Crash in RedHat...
```
Linux ip-172-31-33-28.us-west-2.compute.internal 3.10.0-693.2.1.el7.x86_64 #1 SMP Fri Aug 11 04:58:43 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

>node --version
v6.11.3

solcjs --version
killed
```
any help is appreciated

regards

Sean

**Comment by chriseth** [comment]
It looks like you are running this inside a compute node. Does that node have enough memory?

**Comment by born2net** [comment]
ya it may be under powered (micro instance), will upg today and report back
tx!

**Comment by born2net** [comment]
you were right, a stronger instance fixed it!
tx!!!
