### ISSUE TITLE
0.3.2-81ae2a78 non-determisitic compilation

### ISSUE THREAD

**Issue by colm** [ethereum/solc-js#14]
https://gist.github.com/colm/2ddda1e3e825ae6597a7edde43d28f27

`nodejs --stack-size=64000 compile_brute_force.js`to test if the compiler returns different bytecode. The byte code is hashed. These hashes are printed. All hashes should match.

This may be a bug in solidity which [this PR](https://github.com/ethereum/solidity/pull/536) was ment to resolve.

**Comment by chriseth** [comment]
Yes, this was supposed to be fixed by the given PR. The version you cite is older than the PR. Can you test with latest develop?

**Comment by chriseth** [comment]
Confirmed that we now have identical and deterministic compilation at least for the DAO contract both with and without optimizer in the following versions:
`0.3.3-4dc1cb14` in solc-js (emscripten architecture) and solc (Linux clang architecture), while compilation in solc-js was even performed multiple times in the same instance.
