### ISSUE TITLE
Unable to require('solc') in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by muhammaddadu** [ethereum/solc-js#160]
I am unable to require solc in Ubuntu 16.04
```
Linux ip-172-31-36-63 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

to reproduce, install solc, run node in your CLI and try to require('solc');
```bash
$ node
require('solc')
```

**Comment by axic** [comment]
This is not a lot of information. What error messages do you get?

Note, it seems you are running this on AWS. It is usual that AWS runs out of memory, try a bigger instance.

**Comment by axic** [comment]
Please reopen if it still persists.
