### ISSUE TITLE
Pure functions are allowed to do revert()

### ISSUE THREAD

**Issue by pash7ka** [ethereum/solc-js#163]
May be i am wrong, but i understand that pure functions should not have any side effects. And doing revert() is a side effect.
Here is the test contract:
```
pragma solidity ^0.4.17;
contract Test {
    uint public a;
    function setA(uint _a) public {
        notZero(_a);
        a = _a;
    }
    function notZero(uint v) pure public {
        if(v == 0) revert();
    }
}
```
In my opinion it's compilation should fail. But instead if i don't specify "pure" solcjs generates warning:
```
Test.sol:8:5: Warning: Function state mutability can be restricted to pure
    function notZero(uint v) public {
    ^
Spanning multiple lines.
```

**Comment by axic** [comment]
Can you please reopen this issue on https://github.com/ethereum/solidity ?

I'll comment on it there

**Comment by pash7ka** [comment]
Done: https://github.com/ethereum/solidity/issues/3237
