### ISSUE TITLE
Cannot be imported at compile time

### ISSUE THREAD

**Issue by mimitc123** [ethereum/solc-js#166]
ERROR：
C:\Users\ThinkPad\Desktop>solcjs a.sol --bin --abi --optimize -o
a.sol:7:1: ParserError: Source "github.com/Arachnid/solidity-stringutils/strings.sol" not found: File not supplied initially.
import "github.com/Arachnid/solidity-stringutils/strings.sol";

How to solve？

**Comment by axic** [comment]
This is a missing feature (tracked in #114). You can place the sources locally and replace the github link with a filename. Alternatively I suggest to use https://remix.ethereum.org which supports github imports.
