### ISSUE TITLE
Cannot build on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solc-js#204]
The `prepublish` command does `./downloadCurrentVersion && ./verifyVersion.js`.  This is a shell command that will not work on Windows.  Recommend authoring a single script (`prepublish.js`) that simply executes those two scripts back to back and then run `node prepublish.js`.

**Comment by MicahZoltu** [comment]
I attempted to do this in a naïve way with
```js
require('./downloadCurrentVersion');
require('./verifyVersion');
```
Unfortunately, the first script returns immediately even though it has async work being done.  If this were my project, my recommendation would be to change these two scripts into libraries and then the following at the end:
```js
function doStuff(callback) { ... }

if (require.main === module) {
    doStuff(() => {
        process.exit(1);
    });
}
```
This way, the file can be used either as a library or as a script.  Then the aforementioned prepublish script could be written and used.

**Comment by MicahZoltu** [comment]
Note: If I submit a PR with such changes, is it likely to be accepted?

**Comment by chriseth** [comment]
I think a cleaner version would be to create npm scripts for both of these - is it possible to combine them in that case?

**Comment by MicahZoltu** [comment]
Is it possible to (in a platform independent way) have one npm script reference two other npm scripts to be run in sequence?

**Comment by MicahZoltu** [comment]
Looking more into this, what is the reason those two scripts are separate?  When would you ever want to run the download script without running the verify script?

**Comment by chriseth** [comment]
Good question :)
