### ISSUE TITLE
Generate userdoc/devdoc

### ISSUE THREAD

**Issue by psyfreak** [ethereum/solc-js#209]
Hey,
I am wondering, if it is possible to generate userdoc/devdoc with solcjs?
Maybe this might be already possible by using Output JSON Description?

Looking forward to your answer.

Thank you.

**Comment by yosefd** [comment]
I think it is possible, at least this way:
```javascript
const output = solc.compile(code, 1);
const compiledContract = output.contracts[`:${contractName}`];
var result = {};
result.bytecode = '0x' + compiledContract.bytecode;
result.abi = JSON.parse(compiledContract.interface);
const metadata = JSON.parse(compiledContract.metadata);
result.userdoc = metadata.output.userdoc;
```

**Comment by axic** [comment]
It is also available through the standard json interface, which is the preferred one.

**Comment by rsodre** [comment]
> It is also available through the standard json interface, which is the preferred one.

@axic  and how does one do that from the command line?
