### ISSUE TITLE
When import solc-js to Web Worker, occur error "Maximum call stack size exceeded".

### ISSUE THREAD

**Issue by Hanul** [ethereum/solc-js#218]
When import solc-js to Web Worker, occur error "Maximum call stack size exceeded".
`soljson-v0.4.6+commit.2dabbdf0.js` is ok, but all upper versions have this problem.
Could you find reason?

**Comment by axic** [comment]
Probably that given release was quite big and your VM/browser has a limit on Javascript sizes.

**Comment by peony-ma** [comment]
@Hanul 设置一下 --stack_size=1000000

**Comment by axic** [comment]
Closing this as Remix users would notice if this would be a common issue. Please reopen if it keeps happening.

**Comment by Asone** [comment]
@axic : i just tried it and have the same problem. 

- OS : Debian 9
- Node : v10.7.0
- npm : 6.1.0

It happened a first time on `npm install` of remix-ide and also when trying `npm start`. 

I tried also `npm start --verbose` to see if i could get a more specific stacktrace but no luck. 

Please, feel free to ping me if you want or need any additional information.
