### ISSUE TITLE
Include an option or alternative method which passes the raw strings

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#24]
and doesn't do JSON (de)serialisation.

It could be utilised by anyone using a browser worker, where only primitive types (strings) can be transmitted reliably. Without this option, that results in JSON encoding/decoding twice.

**Comment by chriseth** [comment]
Can you explain a bit more which passing you are referring to?

**Comment by axic** [comment]
```js
  var compile = function (input, optimise, readCallback) {
    var result = '';
    if (readCallback !== undefined && compileJSONCallback !== null) {
      result = compileJSONCallback(JSON.stringify(input), optimise, readCallback);
    } else if (typeof input !== 'string' && compileJSONMulti !== null) {
      result = compileJSONMulti(JSON.stringify(input), optimise);
    } else {
      result = compileJSON(input, optimise);
    }
    return JSON.parse(result);
  }
```

The compile method with JSON stringify & parse.  If solc is used within a web worker, the web worker will have to JSON stringify & parse again.

It would be nice to somehow have a feature where we can turn on/off the JSON stringify & parse.

**Comment by chriseth** [comment]
Yes! My plan is actually to encode everything into json (string) until the very internals of the compiler - because that allows us to recompile easily for verification.

**Comment by axic** [comment]
See comment: https://github.com/ethereum/solc-js/issues/33#issuecomment-314225490
