### ISSUE TITLE
ecrecover return wrong values

### ISSUE THREAD

**Issue by legioner0** [ethereum/solc-js#262]
I found strange behavior of function `ecrecover` in `solc-js` 0.4.24 and 0.4.25 - some input data leads to wrong return value.
Here is project with proof: https://github.com/legioner0/ecrecover-failed
In this project test working in `ganache`, but I started my investigation, when transactions to contract with similar logic on mainnet failed.

**Comment by axic** [comment]
Can you please open an issue on https://github.com/ethereum/solidity ?

**Comment by legioner0** [comment]
done https://github.com/ethereum/solidity/issues/5109
