### ISSUE TITLE
Achieve 100% test coverage on the linker

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#275]
This should be a good first issue.

**Comment by jhokkar** [comment]
@axic I want to work on this. Can I start straightaway?

**Comment by axic** [comment]
Please go head!

There are only 2 lines which are not covered: https://coveralls.io/builds/20170846/source?filename=linker.js

**Comment by jhokkar** [comment]
The regex in line 23 will match for all vaues of `libraryName`. So we can't write a testcase where `parsed` evaluates to a falsey value.

**Comment by axic** [comment]
Then the regex should be fixed :)
