### ISSUE TITLE
Unable to require('solc')

### ISSUE THREAD

**Issue by yendenikhil** [ethereum/solc-js#29]
I am trying to run Ethereum smart contracts on vm.
VM tech: vagrant
host OS: mac osx
vm os: ubuntu trusty
solc version: 
```
vagrant@vagrant-ubuntu-trusty-64:~/repo/sol-00$ solc --version
solc, the solidity compiler commandline interface
Version: 0.3.4-0/RelWithDebInfo-Linux/g++/Interpreter
```

solc-js version: solc@0.3.5

I have created small script called c1.js with just one line 
```javascript 
var solc = require('solc');
```

When I run it using `node c1.js` I get one line result "Killed".

Can you help please?

**Comment by chriseth** [comment]
Where do you get this result from? How much memory does your VM have?

**Comment by axic** [comment]
@yendenikhil can you please reopen and provide more detail if you still have this problem?

**Comment by born2net** [comment]
same issues here :(

>uname -a
Linux ip-172-31-33-28.us-west-2.compute.internal 3.10.0-693.2.1.el7.x86_64 #1 SMP Fri Aug 11 04:58:43 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

node --version
v6.11.3

regards

Sean

**Comment by muhammaddadu** [comment]
Same issue here (on the latest version)
```
Linux ip-172-31-36-63 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

to reproduce, run node in your CLI and try to require('solc');
```bash
$ node
require('solc')
```
