### ISSUE TITLE
Add standard contract support

### ISSUE THREAD

**Issue by Antanukas** [ethereum/solc-js#30]
Is it possible to have standard contracts available during compilation like with CLI --add-std option?

**Comment by redsquirrel** [comment]
@Antanukas Are you referring to https://github.com/androlo/standard-contracts ?

**Comment by Antanukas** [comment]
I'm talking about these https://github.com/ethereum/solidity/blob/31aa67f1caa802817e376745d01e187a26eaaea5/libsolidity/interface/CompilerStack.cpp `StandardSources` that gets added by compiler when `solc --add-std` is specified.

**Comment by chriseth** [comment]
Please don't - I would like to deprecate them.
