### ISSUE TITLE
loadRemoteVersion in solc-js 0.5.0 returns corrupted compiler

### ISSUE THREAD

**Issue by daniyarchambylov** [ethereum/solc-js#302]
I have solc-js 0.5.0 installed on my machine and need to use remote compiler version 0.4.22+commit.4cb486ee.Emscripten.clang

Here is the small snippet code I wrote:
```javascript
solc.loadRemoteVersion(cleanedVersion, function(err, remoteSolc) {
      if (err) {
        return cb(err);
      }
      console.log('>>>>>>>>>>>>>>>>>>>>>>>>>', remoteSolc.semver())
      console.log(remoteSolc)
      const compiled = remoteSolc.compile(solfile, 1);
      return cb(null, compiled);
});
```
This is the output: 
```
>>>>>>>>>>>>>>>>>>>>>>>>> 0.4.22+commit.4cb486ee.Emscripten.clang
{ version: [Function],
  semver: [Function: versionToSemver],
  license: [Function],
  lowlevel:
   { compileSingle: [Function],
     compileMulti: [Function],
     compileCallback: [Function: compileJSONCallback],
     compileStandard: [Function: compileStandard] },
  features:
   { legacySingleInput: true,
     multipleInputs: true,
     importCallback: true,
     nativeStandardJSON: true },
  compile: [Function: compileStandardWrapper],
  compileStandard: [Function: compileStandardWrapper],
  compileStandardWrapper: [Function: compileStandardWrapper],
  loadRemoteVersion: [Function: loadRemoteVersion],
  setupMethods: [Function: setupMethods] }
/usr/src/app/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!

AssertionError [ERR_ASSERTION]: Invalid callback specified.
```

I installed compiler version 0.4.25 and everything works as expected

I looked at the code of wrapper.js  both for 0.4.22 and 0.5.0 and it looks like method `compile` does not point to downloaded compiler version 0.4.22, in face it points to 0.5.0

![wrapper.js for version 0.5.0](https://user-images.githubusercontent.com/7006388/49163248-da4cbf80-f356-11e8-8ad1-f52be53edd39.jpeg)
![wrapper.js for version 0 4 22](https://user-images.githubusercontent.com/7006388/49163286-ee90bc80-f356-11e8-9ee8-91eed84076fc.jpeg)

**Comment by axic** [comment]
>       const compiled = remoteSolc.compile(solfile, 1);

This is not how to use the compiler, please see the README for instructions.

**Comment by axic** [comment]
Sorry, that example is outdated. See https://github.com/ethereum/solc-js#from-version-050

We need to clean up the readme, tracked in #297.

**Comment by daniyarchambylov** [comment]
@axic It seems to you misunderstood the problem here.
When I install solc@0.4.22 and call `solc.compile("pragma solidity ^0.4.22; contract t { function g() {} }", 1)` everything runs correctly. But when I install solc@0.5.0 and do
```javascript
solc.loadRemoteVersion('v0.4.22+commit.4cb486ee', function (err, solcSnapshot) {
	if (err) {
		// An error was encountered, display and quit
	}
	var output = solcSnapshot.compile("pragma solidity ^0.4.22; contract t { function g() {} }", 1)
})
```
I expect it to run also, since I'm using remote compiler version 0.4.22, but in reality it fails looks like properties of 0.5.0 is used instead

**Comment by axic** [comment]
0.5.0 changed the API, it doesn't have the API you are trying to call anymore.

**Comment by daniyarchambylov** [comment]
@axic that's wrapper.js for version 0.5.0
https://github.com/ethereum/solc-js/blob/7086f78307bcbdfe5fe3379198a48eff5ba547de/wrapper.js#L233

I see that loadRemoteVersion is present. Which API are you talking about?
loadRemoteVersion in 0.5.0 is broken. Please fix it!

**Comment by axic** [comment]
`compile` is different, not `loadRemoteVersion`.

**Comment by daniyarchambylov** [comment]
Since I'm loading `v0.4.22+commit.4cb486ee` shouldn't `solcSnapshot` have `compile` same as `compile` in solc@0.4.22?

**Comment by axic** [comment]
No. All these wrappers are specific to solc-js' version and not to what you are loading.

**Comment by axic** [comment]
`loadRemoteVersion` only loads the binary, doesn't reloads `solc-js`.

**Comment by daniyarchambylov** [comment]
So how can I use `loadRemoteVersion` on 0.5.0 to compile solidity file for pragma <0.5.0?
And what is the purpose of `loadRemoteVersion` anyway? I'm a bit confused now.

**Comment by axic** [comment]
I'm confused about what you are confused about.

There is a single interface you can use, `solc.compile` with standard JSON in 0.5.0.

`loadRemoteVersion` swaps the underlying binary with a different version.

**Comment by daniyarchambylov** [comment]
> loadRemoteVersion swaps the underlying binary with a different version.
So that means using that binary I could compile for older pragma versions right?
This is what I'm trying to achieve and according to Readme I'm doing everything right.

Could you please insert small snippet how can I use loadRemoteVersion from 0.5.0 to get binary file for 0.4.22 and compile solidity file with pragma 0.4.22?

**Comment by axic** [comment]
```
solc.loadRemoteVersion('latest', function (err, solcSnapshot) {
  let ret = JSON.parse(solcSnapshot.compile(JSON.stringify(<Standard JSON input here>)))
  // ret is a JSON with the "Standard JSON output"
}
```

**Comment by daniyarchambylov** [comment]
Thanks, I 'll try that

**Comment by axic** [comment]
>  This is what I'm trying to achieve and according to Readme I'm doing everything right.

I've mentioned already the README needs to be cleaned up, it is misleading.

**Comment by ToJen** [comment]
@daniyarchambylov did you get that to work? i want to implement something similar

**Comment by axic** [comment]
Still not sure why you are passing `1`? Documentation says that it takes a JSON and an import callback function. Just use `compile(JSON.stringify({...}))` as suggested in https://github.com/ethereum/solc-js/issues/302#issuecomment-443182849.
