### ISSUE TITLE
browserify -- provide instructions and best practices

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/solc-js#31]
Please provide the browserify instructions and best practices. Many people will use this module in the browser. We should have a solid known way to browserify everything properly.

i.e. something like this:

```
browserify -s 'solc' -e . -o ./dist/solc-bundle.js
```

**Comment by axic** [comment]
I don't think this package has any specific browserify requirements.

**Comment by cofdev0** [comment]
Could you please explain what the best practice is to use solc in Jest tests?

Requiring solc in Jest tests also leads to "Uncaught TypeError: soljson.cwrap is not a function"

**Comment by axic** [comment]
I am not able to reproduce that problem. Browserify works for me locally. Are you sure you have a local `soljson.js`? Run `npm run downloadsolc` to download one.

**Comment by wighawag** [comment]
Get the same issue with `jest` :

in my js test file :

```const solc = require('solc');```

fails with:

```
Uncaught TypeError: soljson.cwrap is not a function
```

**Comment by dangell7** [comment]
I'm where you are lol.

Webpack, react redux app. This is my only hangup. Thinking about setting up an api to a server just to get the abi and bytecode for a contract. lol

**Comment by woodydeck** [comment]
Yea, can't get it to work. Does anyone have examples of it working? I just need the bytecode, nothing else on the frontend.

I tried browser-solc, but you need to parse the results, and there is no documentation to how it actually outputs.

**Comment by jmahhh** [comment]
So am I correct in thinking this + browserify/webpack is broken?

**Comment by max-block** [comment]
I have the same error "Uncaught TypeError: soljson.cwrap is not a function" in my Jest test files.

Without Jest it works fine. Is there anyone who have found a solution for Jest?

**Comment by GrandSchtroumpf** [comment]
Same error here. I'm in Angular (Webpack). I downloaded the soljson.js bin, and did : 
```
const soljson = require('./soljson.js');
console.log(soljson); // Object{}
```
I saw the electron warning, but it doesn't seems relevant in this case.

**Comment by mattiaerre** [comment]
I've been able to fix this issue w/ Jest adding the following setup in my package.json file:

```jsonn
"jest": {
    "testEnvironment": "node"
  }
```

HTH @max-block

**Comment by GrandSchtroumpf** [comment]
If you want to import solc in the browser you need to : 
- 1 : Add that to your `index.html` : 
```html
    <script type="text/javascript" src="https://ethereum.github.io/solc-bin/bin/list.js"></script>
    <script type="text/javascript" src="https://ethereum.github.io/solc-bin/bin/{{ SOLC VERSION }}.js"></script>
```
This will load 3 global variables : `soljsonSources`, `soljsonReleases` and `Module`.
Note: Check the url for the version of solc you want to use [here](https://github.com/ethereum/solc-bin/tree/gh-pages/bin).

- 2 : Use a solc wrapper : 
By default solc uses its `soljson.js` inside its wrapper. I don't know why (yet), but it doesn't works in a browser. So you need to provide `window.Module` inside the wrapper : 
```js
import * as wrapper from 'solc/wrapper'; // OR const solc = require('solc/wrapper');

const solc = wrapper(window.Module);
const compiled = solc.compile(/* Your contract */);
```

_If someone knows why the default `soljson.js` is not loaded correctly in a browser I'm curious to know why._

**Comment by axic** [comment]
@GrandSchtroumpf could you submit a README update?

**Comment by GrandSchtroumpf** [comment]
Sure. Btw, do you know why the default `sol.json.js` is not loaded in a browser?
