### ISSUE TITLE
After 'npm install -g solc' it tells me '/bin/sh: solc: command not found'

### ISSUE THREAD

**Issue by davesag** [ethereum/solc-js#32]
I just upgraded `cpp-ethereum` (via `brew upgrade cpp-ethereum`) and now `solc` is borked.

I tried `npm uninstall -g solc` and then `npm install -g solc@latest` but alas.

Is there some setting somewhere I need to change to reconnect `cpp-ethereum` and `solc` since the update?

**Comment by axic** [comment]
This package doesn't install a binary, so it shouldn't cause any issues. (There is a proposed change https://github.com/ethereum/solc-js/pull/27, which will make `solcjs` available as a tool.)

**Comment by axic** [comment]
@davesag can you please reopen and provide more detail if this is still a problem?
