### ISSUE TITLE
How to get the bytecode and abi from the Json formatted output with solc@0.5.0 ?

### ISSUE THREAD

**Issue by JoshuaQYH** [ethereum/solc-js#329]

**Comment by iheqi** [comment]
em... So how to get?I want to know too.

**Comment by JoshuaQYH** [comment]
> em... So how to get?I want to know too.

Just check the readme of this repo.

**Comment by iheqi** [comment]
> > em... So how to get?I want to know too.
> 
> Just check the readme of this repo.

output: Imooc.json, contract: Course
abi: `Imooc.Course.abi`
bytecode: `Imooc.Course.evm.bytecode.object`

Just like that? It can work, but it is too long.

**Comment by JoshuaQYH** [comment]
> > > em... So how to get?I want to know too.
> > 
> > 
> > Just check the readme of this repo.
> 
> output: Imooc.json, contract: Course
> abi: `Imooc.Course.abi`
> bytecode: `Imooc.Course.evm.bytecode.object`
> 
> Just like that? It can work, but it is too long.

If you wanna compile and deploy contract with abi and bytecode, you can check my [blog](https://blog.csdn.net/CVSvsvsvsvs/article/details/85498852). If it cannot help for you, I am sorry about that because I seldom learn ethereum knowledge.

**Comment by iheqi** [comment]
> > > > em... So how to get?I want to know too.
> > > 
> > > 
> > > Just check the readme of this repo.
> > 
> > 
> > output: Imooc.json, contract: Course
> > abi: `Imooc.Course.abi`
> > bytecode: `Imooc.Course.evm.bytecode.object`
> > Just like that? It can work, but it is too long.
> 
> If you wanna compile and deploy contract with abi and bytecode, you can check my [blog](https://blog.csdn.net/CVSvsvsvsvs/article/details/85498852). If it cannot help for you, I am sorry about that because I seldom learn ethereum knowledge.

old iron, double click six six six. 哈哈哈
