### ISSUE TITLE
Link to compiler with SRI

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solc-js#334]
Currently [in the README](https://github.com/ethereum/solc-js/blob/master/README.md#browser-usage):

> Add the version of solc you want to use into index.html:
>
> <script type="text/javascript" src="https://solc-bin.ethereum.org/bin/{{ SOLC VERSION }}.js"></script>
> (Alternatively use https://solc-bin.ethereum.org/bin/soljson-latest.js to get the latests version.)

This is not a security best practice. We should promote security best practices by providing a list of specific URLs and SRI hashes. Some people may prefer convenience over security and not use SRI, we can explain to them that they are taking on more risk that way.

**Comment by r0qs** [comment]
Fixed by #658.
