### ISSUE TITLE
Is soljson.js a compiler? where can i found the c/cpp source code of soljson.js.

### ISSUE THREAD

**Issue by mxito3** [ethereum/solc-js#338]
Hello, Can somebody tell me what role of file `soljson.js`  plays? Is it a  solidity compiler with specified version?  
One more question is where can I found the `c/cpp` source code which `soljson.js` generated from.

**Comment by axic** [comment]
It is in the readme: https://github.com/ethereum/solidity

**Comment by mxito3** [comment]
@axic Thanks.I have read it but it's not what I want. I want the source code of solidity compiler which written in c/cpp. And I want to do some change base on that.

**Comment by axic** [comment]
That is where the source, written in C++, is.

**Comment by mxito3** [comment]
> That is where the source, written in C++, is.

Oh. It's my fault. Thank you very much.
