### ISSUE TITLE
Provide a real linker

### ISSUE THREAD

**Issue by chriseth** [ethereum/solc-js#36]
This depends on functionality in the compiler: https://github.com/ethereum/solidity/issues/863

**Comment by Levino** [comment]
Yes, please make high priority. The current solc-js is unusable. Have to switch to installing solc and run bash from node.

**Comment by chriseth** [comment]
In the meantime, you can write your own linker by following this code: https://github.com/ethereum/browser-solidity/blob/ab0593386a761e9755e3c79968767ffa8ad2fd82/src/universal-dapp.js#L634

**Comment by axic** [comment]
We kind of have this with `linkBytecode`. Also `compileStandard()` introduces a much better way.
