### ISSUE TITLE
Memory leak with loadRemoteVersion with 0.5.11

### ISSUE THREAD

**Issue by gauravsquadx** [ethereum/solc-js#379]
I am using this package inside an Express app. 

I see

`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

when . i try to use `solc.loadRemoteVersion` for compilation. Is there any workaround, as loadRemoteVersion pipes the remote javascript to a memory stream.

**Comment by gauravsquadx** [comment]
solc version 0.5.11

**Comment by axic** [comment]
@gauravsquadx please reopen if this is a recurring issue or if you can provide a reproducible test case (make sure to include information about the environment, eg. OS, memory, etc.)
