### ISSUE TITLE
on what parameter solc making a sequence of method in abi

### ISSUE THREAD

**Issue by Nayyar525** [ethereum/solc-js#387]
I have one small contract :

pragma solidity >=0.4.0 <0.7.0;

contract demo {
    uint storedData;
function set(uint x) public returns(bool sufficient){
        storedData = x;
		return true;
}
    function get() public view returns (uint) {
        return storedData;
    }       
}

in this when i compile and get the sequence of function are like same as written in the contract i.e  in abi at 0 will be set 
and at 1 will be get 

But now if i change the name of the method is like 

pragma solidity >=0.4.0 <0.7.0;
contract demo {
    uint storedData;
function fun_1(uint x) public returns(bool sufficient){
        storedData = x;
		return true;   }
    function fun_2() public view returns (uint) {
        return storedData;
    }  
}

Now after compile by solc the abi is giving at 0 i am fun_2 and at 1 i am fun_1 

can you please let me why this is happened and what parameter i have to take care so that the  function in second contract should come in an sequence

**Comment by axic** [comment]
The ABI doesn't correspond to the order of functions defined in the contract source. In the 0.5.12 release it will follow this:
> ABI Output: Change sorting order of functions from selector to kind, name.

**Comment by Nayyar525** [comment]
@axic But according to the above SC the fun_1 should be come at place 0 in the abi but its comes at place 1. can you please let me know why this happen.

Do you have any example for the same where it's shows this :**ABI Output: Change sorting order of functions from selector to kind, name.**

**Comment by axic** [comment]
The `selector` is the hash of the function name. In any case, the sorted order doesn't intend to reflect the order in the source file.
