### ISSUE TITLE
how to run solc@0.4.0

### ISSUE THREAD

**Issue by zhouzhou84** [ethereum/solc-js#413]
the remix-ide compiles the file is too slow and receives no response. 
So I want to compile sol file with solc@0.4.0, but when using  `npm install -g solc@0.4.0`, the soljson.js is a wrong file , 
the content is html-style, you can run the command `npm install -g solc@0.4.0` and check /solc/soljson.js, 
how can I complie files with solc@0.4.0?

**Comment by erak** [comment]
@zhouzhou84 Thanks again! Since this report is basically the same as https://github.com/ethereum/solc-js/issues/412, I'll close it now and comment on the other one.
