### ISSUE TITLE
Make solcjs have better output

### ISSUE THREAD

**Issue by Denton-L** [ethereum/solc-js#42]
Currently, `solcjs` has almost no output. Even if a build errors out, it will just silently exit and simply not make any files.

A desired behaviour would be to have `solcjs` print out all of the error messages that caused the build to fail and then return a non-zero exit code, instead.

**Comment by axic** [comment]
@Denton-L can you draft up the desired behaviour & output here?

**Comment by chevdor** [comment]
See #22

**Comment by chevdor** [comment]
Hi @Denton-L I think this issue can be closed and we keep on tracking in #22 which is the same issue.

**Comment by chevdor** [comment]
See #61

**Comment by axic** [comment]
Fixes by #102.
