### ISSUE TITLE
Array slicing syntax for calldata arrays does not compile

### ISSUE THREAD

**Issue by gitpusha** [ethereum/solc-js#437]
Hi, 
Sorry for keeping this short: just wanted to bring this to your attention in case of relevance to your repo:
Excerpt from the issue prose I posted on solidity gitter:

> (at)chriseth My `solcjs` `0.6.0` compiler gives me this error log when trying to compile this new syntax (array slicing of calldata arrays)

![image](https://user-images.githubusercontent.com/36712489/71167700-73e25a00-2255-11ea-8fd4-402fb9e2e04a.png)

![image](https://user-images.githubusercontent.com/36712489/71167637-58774f00-2255-11ea-9c1c-0bc1d8f52eb9.png)

> as soon as I remove the line `bytes4 selector = abi.decode(_actionPayloadWithSelector[:4], (bytes4));` everything compiles again
> any hints? (I am using `npx buidler compile` which I believe just fetches `solcjs` from npm for compilation)

> (at)gitpusha (from (at)chriseth) I guess the `antlr parser` has to be updated, but you might want to try `(bytes4,)`

`(bytes 4,)` did not work...

**Comment by axic** [comment]
The error message seems to be coming from `solidity-parser-antlr`, which is a different project. `solc-js` or `solidity` don't use it. You need to reach out to the authors of solidity-parser-antlr.

**Comment by gitpusha** [comment]
thanks for clarifying!
