### ISSUE TITLE
solc-js throws an error with just a number; trouble compiling strings.js

### ISSUE THREAD

**Issue by tcoulter** [ethereum/solc-js#44]
When you try to compile [solidity stringutils's strings.sol](https://github.com/Arachnid/solidity-stringutils), solc-js will throw an error with only a number as its error message. I've created a github project showing how you can reproduce the error, link below. This error was originally posted on Truffle's issue tracker [here](https://github.com/ConsenSys/truffle/issues/251).

https://github.com/tcoulter/solc-result-bug

> $ ./index.js
> 
> /Users/tim/Documents/workspace/Consensys/solcbug/node_modules/solc/soljson.js:1 (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath"normalize";var ret=nodeFS["readFil
> 6042264
> 
> $

**Comment by axic** [comment]
I think those numeric errors are C++ exceptions not properly handled. It is printed by Emscripten and not the `console.log` lines you have in your demo code.

**Comment by tcoulter** [comment]
> not the console.log lines you have in your demo code
Correct. Those were for me to ensure they were never reached. They can be removed.

**Comment by axic** [comment]
@tcoulter were you able to somehow reduce string.sol to a smaller instance which still has this problem?

**Comment by tcoulter** [comment]
Ah, my bad. I didn't try.

**Comment by tcoulter** [comment]
I can likely give it a shot later today.

**Comment by axic** [comment]
@tcoulter moved to https://github.com/ethereum/solidity/issues/971 - can you please comment your findings there later?
