### ISSUE TITLE
How does one install an older version of solc

### ISSUE THREAD

**Issue by denismp** [ethereum/solc-js#444]
I currently have 0.6.1 installed with the "npm i solc".  How do I install version 0.5.0?

**Comment by chriseth** [comment]
Usually, you use the latest version of the npm package and load an older compiler using the method described here: https://github.com/ethereum/solc-js#using-a-legacy-version

**Comment by denismp** [comment]
So that looks like a javascript solution.  I am using the Visual Studio Code with the solidity plugin.  I added the solc with the "npm i solc", which is being used by VSC to compile my solidity code, and it does not support versions older than 0.6.1.

>npm solc --version
6.13.4

Given that, how do I get VSC to recognize pragma solidity ^0.5.5 in my solidity code?

Is there a configuration file or some setting that I need to add or modify to specify the pragma that I wish to use?

**Comment by denismp** [comment]
I found the solution to this issue.  Create the file .vscode/settings.json and enter: 
{
    "solidity.compileUsingRemoteVersion": "0.5.5+commit.47a71e8f"
}
This will cause VSC to compile with the 0.5.5 version of solc.

**Comment by gwalen** [comment]
to update specific version with npm (it will also downgrade if you have higher version)
`npm --install g solc@0.7.6`

**Comment by gabrielsalvador** [comment]
> npm --install g solc@0.7.6

you meant "npm install g solc@0.7.6 " perhaps ?
