### ISSUE TITLE
Install often times out due to github pages rate limit

### ISSUE THREAD

**Issue by samsondav** [ethereum/solc-js#445]
We're having trouble building contracts on our CI machine. The build fails very often with a rate limiting error:

```
 | FetchError: response timeout at https://ethereum.github.io/solc-bin/bin/soljson-v0.4.24+commit.e67f0147.js over limit: 20000
 |     at Timeout._onTimeout (/chainlink/node_modules/node-fetch/lib/body.js:117:12)
```

Is there some way we can provide a cached version of the soljson binaries, or supply a different url to work around this?

**Comment by chriseth** [comment]
You can use the method described here to use a local "binary": https://github.com/ethereum/solc-js#using-a-legacy-version

**Comment by samsondav** [comment]
@chriseth thanks, but this doesn't really help because this library is called from a third party library (specifically truffle and `@0x/sol-compiler`). We don't have any control over how that is called.

In addition, we still want to remotely load the latest version - just have it be reliable. Check PR #446 for a solution.

**Comment by cameel** [comment]
@samsondav @jleeh Just FYI: we're switching the download links to https://solc-bin.ethereum.org (see #479 for details). Currently the domain still points at GH pages so you may temporarily experience the flakiness again but we're in the process of switching that over to an Amazon S3 bucket mirroring `solc-bin` that won't have these limitations.
