### ISSUE TITLE
solcjs cli and solc package compilation results in different deployment costs

### ISSUE THREAD

**Issue by petscheit** [ethereum/solc-js#462]
While working with the solcjs cli I realized that when compiling with pretty much default settings `(solcjs --abi --bin contract.sol)` the deployment of the contract will have higher gas costs then when compiling with the solc npm package. This can be observed when compiling and deploying with remix and comparing the results to compiling with solcjs and then deploying with web3. 
The difference is quite significant, for a large contract I'm working with 1178812 vs. 1085126 gas, so a difference of 93686 gas. When activating the optimizer, the gas costs for deployment match, so there is no issue when running with the optimizer activated.
I'm guessing this is related to the default settings of the cli and js package. Please consider changing the default settings, so the default config of solcjs matches the solc package and in effect remix.

Solc version: 0.6.6

**Comment by chriseth** [comment]
The default settings should be the same. Can you provide example input that exhibits this behaviour? Did you use released version for both compilers?

**Comment by petscheit** [comment]
Turned out to be an error on my side. The contract with the higher deployment costs was using ABIv2 and used a struct as an input parameter, the other contract didn't and constructed the struct in the function. It's still a bit odd, that passing a struct as a parameter uses quite significantly more gas then passing separate parameters and constructing the struct. Then again it's still in beta. Closing this as there is no problem with the compiler
