### ISSUE TITLE
invalid soljson.js file after upgrade to v0.4.0

### ISSUE THREAD

**Issue by naddison36** [ethereum/solc-js#47]
Can not require solc after upgrading to version 0.4.0. Error message: `SyntaxError: Unexpected token <`

I can see the `soljson.js` file contains HTML with an error message
`<h1>404</h1>
      <p><strong>File not found</strong></p>

      <p>
        The site configured at this address does not
        contain the requested file.
      </p>`

the `soljson.js` file is not in the repo so this must be dynamically generated but I don't know how.

Steps to reproduce:

1. Update dependency in `package.json` to `"solc":"^0.4.0",`
2. Run `npm install solc`
3. compile project that uses the solc module. eg https://github.com/juanfranblanco/vscode-solidity

**Comment by chriseth** [comment]
Sorry about that, will fix it with 0.4.1 upcoming today.
