### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by guyinthetie** [ethereum/solc-js#496]
This is an exercise from a slightly dated udemy course. As such, I'm using the last known good version of solc 0.4.25 to have worked with the lesson.

Testing an inbox contract on the ethereum ganache-cli network. Test should return the sample addresses in my ganache-cli. Using *npm run test* I get the RangeError. 

**What I've tried**
After reviewing and rewriting everything, I went out and found completed code from other students at Github and replaced all of my code with theirs. Same error during *run test*

----------
**Environment**
Npm 6.14.7, Node 14.7.0, Web3 1.3.0, Mocha 8.2.0, Solc 0.4.25, Ganache-cli 6.12.0

**File structure**
contracts
-Inbox.sol
node_modules
-test
-Inbox.test
compile
package

**Inbox.test**

    const assert = require('assert');
    const ganache = require('ganache-cli');
    const Web3 = require('web3');
    const web3 = new Web3(ganache.provider());
    const {interface, bytecode} = require('../compile');
    
    let accounts;
    let inbox;
    
    beforeEach (async () => {
    
     //Get a list of all accounts
    accounts = await web3.eth.getAccounts();
    
     //Use one of those accounts to deploy the contract
     inbox = await new web3.eth.Contract(JSON.parse(interface))
        .deploy({ data: bytecode, arguments: ['Hi there!']})
        .send({ from: accounts[0], gas: '1000000'});
    
    });
    
    //Test result
    describe('Inbox', () => {
        it('Unlocked accounts', () => {
         console.log(inbox);
        });
    });

**compile**

    const path = require('path');
    const fs = require('fs');
    const solc = require('solc');
    const inboxPath = path.resolve(__dirname, 'contracts', 'Inbox.sol');
    const source  = fs.readFileSync(inboxPath, 'utf8');

    module.exports = solc.compile(source,1).contracts[':Inbox'];

**Inbox-sol**
```
pragma solidity ^0.4.17;

contract Inbox {
        string public message;
        
        function Inbox (string initialMessage) public {
            message = initialMessage;
        }
        
        function setMessage(string newMessage) public {
            message = newMessage;           
        }

}
```

**Error**
> > inbox@1.0.0 test C:\Sites\Inbox
> > mocha
> 
> 
> RangeError: Maximum call stack size exceeded
>     at Object.$db [as dynCall_viiiiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:120931)
>     at invoke_viiiiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1118145)
>     at Array.pva (C:\Sites\Inbox\node_modules\solc\soljson.js:13:29030)
>     at Object.M9a [as dynCall_vi] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:99033)
>     at invoke_vi (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1114949)
>     at Array.xta (C:\Sites\Inbox\node_modules\solc\soljson.js:10:704784)
>     at Object.Dfb [as dynCall_iii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:130740)
>     at invoke_iii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1119380)
>     at Array.vta (C:\Sites\Inbox\node_modules\solc\soljson.js:10:703080)
>     at Object.Yfb [as dynCall_iiiiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:131900)
>     at invoke_iiiiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1119630)
>     at zua (C:\Sites\Inbox\node_modules\solc\soljson.js:10:861319)
>     at rra (C:\Sites\Inbox\node_modules\solc\soljson.js:10:535864)
>     at Array.pqa (C:\Sites\Inbox\node_modules\solc\soljson.js:10:461138)
>     at Object.Ahb [as dynCall_iiiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:139268)
>     at invoke_iiiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1120744)
>     at Array._pa (C:\Sites\Inbox\node_modules\solc\soljson.js:10:406352)
>     at Object.xjb [as dynCall_viiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:147059)
>     at invoke_viiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1122035)
>     at Array._pa (C:\Sites\Inbox\node_modules\solc\soljson.js:10:403166)
>     at Object.xjb [as dynCall_viiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:147059)
>     at invoke_viiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1122035)
>     at Array.Zpa (C:\Sites\Inbox\node_modules\solc\soljson.js:10:402375)
>     at Object.Yfb [as dynCall_iiiiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:131900)
>     at invoke_iiiiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1119630)
>     at Array.T_ (C:\Sites\Inbox\node_modules\solc\soljson.js:8:535287)
>     at Object.xjb [as dynCall_viiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:147059)
>     at invoke_viiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1122035)
>     at Array.Kv (C:\Sites\Inbox\node_modules\solc\soljson.js:9:57525)
>     at Object.Vhb [as dynCall_viii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:140893)
>     at invoke_viii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1120997)
>     at Array.Jv (C:\Sites\Inbox\node_modules\solc\soljson.js:9:48313)
>     at Object.Vab [as dynCall_ii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:102828)
>     at invoke_ii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1115678)
>     at Array.be (C:\Sites\Inbox\node_modules\solc\soljson.js:6:76407)
>     at Object.Vhb [as dynCall_viii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:140893)
>     at invoke_viii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1120997)
>     at Array.ce (C:\Sites\Inbox\node_modules\solc\soljson.js:6:107456)
>     at Object.Vhb [as dynCall_viii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:140893)
>     at invoke_viii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1120997)
>     at Array.ed (C:\Sites\Inbox\node_modules\solc\soljson.js:6:11782)
>     at Object.xjb [as dynCall_viiii] (C:\Sites\Inbox\node_modules\solc\soljson.js:12:147059)
>     at invoke_viiii (C:\Sites\Inbox\node_modules\solc\soljson.js:1:1122035)
>     at $c (C:\Sites\Inbox\node_modules\solc\soljson.js:6:1664)
>     at ccallFunc (C:\Sites\Inbox\node_modules\solc\soljson.js:1:8196)
>     at C:\Sites\Inbox\node_modules\solc\soljson.js:1:8502
>     at Object.compile (C:\Sites\Inbox\node_modules\solc\wrapper.js:77:16)
>     at Object.<anonymous> (C:\Sites\Inbox\compile.js:7:23)
>     at Module._compile (internal/modules/cjs/loader.js:1256:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
>     at Module.load (internal/modules/cjs/loader.js:1105:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:967:14)
>     at Module.require (internal/modules/cjs/loader.js:1145:19)
>     at require (internal/modules/cjs/helpers.js:75:18)
>     at Object.<anonymous> (C:\Sites\Inbox\test\Inbox.test.js:5:31)
>     at Module._compile (internal/modules/cjs/loader.js:1256:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
>     at Module.load (internal/modules/cjs/loader.js:1105:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:967:14)
>     at Module.require (internal/modules/cjs/loader.js:1145:19)
>     at require (internal/modules/cjs/helpers.js:75:18)
>     at Object.exports.requireOrImport (C:\Sites\Inbox\node_modules\mocha\lib\esm-utils.js:20:12)
>     at Object.exports.loadFilesAsync (C:\Sites\Inbox\node_modules\mocha\lib\esm-utils.js:33:34)
>     at Mocha.loadFilesAsync (C:\Sites\Inbox\node_modules\mocha\lib\mocha.js:431:19)
>     at singleRun (C:\Sites\Inbox\node_modules\mocha\lib\cli\run-helpers.js:125:15)
>     at exports.runMocha (C:\Sites\Inbox\node_modules\mocha\lib\cli\run-helpers.js:190:10)
>     at Object.exports.handler (C:\Sites\Inbox\node_modules\mocha\lib\cli\run.js:362:11)
>     at C:\Sites\Inbox\node_modules\mocha\node_modules\yargs\lib\command.js:241:49
> npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! inbox@1.0.0 test:
> `mocha` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the
> inbox@1.0.0 test script. npm ERR! This is probably not a problem with
> npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR!    
> C:\Users\Martin\AppData\Roaming\npm-cache\_logs\2020-10-28T17_06_58_730Z-debug.log

**Error log**
> 0 info it worked if it ends with ok 1 verbose cli [ 1 verbose cli  
> 'C:\\Program Files\\nodejs\\node.exe', 1 verbose cli   'C:\\Program
> Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js', 1 verbose cli  
> 'run', 1 verbose cli   'test' 1 verbose cli ] 2 info using npm@6.14.7
> 3 info using node@v14.7.0 4 verbose run-script [ 'pretest', 'test',
> 'posttest' ] 5 info lifecycle inbox@1.0.0~pretest: inbox@1.0.0 6 info
> lifecycle inbox@1.0.0~test: inbox@1.0.0 7 verbose lifecycle
> inbox@1.0.0~test: unsafe-perm in lifecycle true 8 verbose lifecycle
> inbox@1.0.0~test: PATH: C:\Program
> Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Sites\Inbox\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Program
> Files (x86)\Common
> Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
> Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program
> Files\dotnet\;C:\Users\Martin\AppData\Local\Microsoft\WindowsApps;C:\Users\Martin\AppData\Roaming\npm;C:\Users\Martin\AppData\Local\Programs\Microsoft
> VS Code\bin;C:\Users\Martin\.dotnet\tools 9 verbose lifecycle
> inbox@1.0.0~test: CWD: C:\Sites\Inbox 10 silly lifecycle
> inbox@1.0.0~test: Args: [ '/d /s /c', 'mocha' ] 11 silly lifecycle
> inbox@1.0.0~test: Returned: code: 1  signal: null 12 info lifecycle
> inbox@1.0.0~test: Failed to exec test script 13 verbose stack Error:
> inbox@1.0.0 test: `mocha` 13 verbose stack Exit status 1 13 verbose
> stack     at EventEmitter.<anonymous> (C:\Program
> Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:314:20) 13
> verbose stack     at ChildProcess.<anonymous> (C:\Program
> Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:314:20) 13
> verbose stack     at maybeClose (internal/child_process.js:1051:16) 13
> verbose stack     at Process.ChildProcess._handle.onexit
> (internal/child_process.js:287:5) 14 verbose pkgid inbox@1.0.0 15
> verbose cwd C:\Sites\Inbox 16 verbose Windows_NT 10.0.18363 17 verbose
> argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
> Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test" 18
> verbose node v14.7.0 19 verbose npm  v6.14.7 20 error code ELIFECYCLE
> 21 error errno 1 22 error inbox@1.0.0 test: `mocha` 22 error Exit
> status 1 23 error Failed at the inbox@1.0.0 test script. 23 error This
> is probably not a problem with npm. There is likely additional logging
> output above. 24 verbose exit [ 1, true ]

**Comment by chriseth** [comment]
Can you provide the source code of the contracts?

**Comment by guyinthetie** [comment]
Updated

**Comment by guyinthetie** [comment]
Ended up uninstalling solc 0.4.25 and installing 0.4.17 and it works.
