### ISSUE TITLE
Expose AST w/o import processing

### ISSUE THREAD

**Issue by tcoulter** [ethereum/solc-js#5]
I'd like to use `solc`'s abstract syntax tree to evaluate imports and to eventually extend the import functionality using custom imports (i.e., `import "Foo";` would pull Foo's source from a package manager). Unfortunately, when creating the abstract syntax tree `solc` evaluates imports which, of course, can't be resolved in this case. In response I've created my own [solidity-parser project](https://github.com/ConsenSys/solidity-parser), but there's no use maintaining two sets of code and I'd very much like to use the canonical AST. Can you expose a function that creates an abstract syntax tree without the need to resolve imports? Thanks!

**Comment by axic** [comment]
You do get the missing import statements returned by solc. There's a callback when a missing import reference is found.

**Comment by tcoulter** [comment]
@axic Can you elaborate? It doesn't seem like this is in any of the documentation.

**Comment by axic** [comment]
It is not documented yet as it is not fully working.

You can pass a callback method to `compile(input, optimise, callback)`, where the callback takes the import path as a parameter and returns the source code as a string. Processing the returned string in the C++ part sometimes doesn't work well. 

At least getting the missing imports work reliably and that is how browser-solidity does it: it builds a list of missing imports by re-running the compiler. It might take a few iterations so it is only a workaround in that way. See https://github.com/chriseth/browser-solidity/blob/gh-pages/assets/js/app.js#L626.

(Here was the original issue for it: https://github.com/chriseth/browser-solidity/issues/84. Might have some useful details.)

**Comment by axic** [comment]
@tcoulter I do think having an alternate implementation of the Solidity syntax in PEG is very useful and shouldn't be abandoned. Is your implementation supporting all language constructs or only import statements?

I was toying with the idea while back to have a try at an alternative compiler for the Solidity syntax, this might be a good starting point.  At this stage it isn't a sane project to do though, but might make sense down the line in a couple of years.

**Comment by tcoulter** [comment]
@axic It aims to support all language constructs, and it supports many of them (i.e., it at least parses everything in https://github.com/ConsenSys/solidity-parser/blob/master/test/doc_examples.sol). There's still work to be done to make the AST less verbose and more useful when these constructs are parsed, however. 

Regarding the alternate compiler: Awesome, glad I could help!

**Comment by axic** [comment]
@tcoulter I don't think I will be able to allocate any time to that idea in the forseeable future. Trying to encourage you not to drop your PEG parser in case someone comes along writing a new compiler :smiley:

**Comment by tcoulter** [comment]
Not discouraged yet. :)

**Comment by axic** [comment]
@tcoulter fixed the import callback, see #7

**Comment by axic** [comment]
This is now possible using `compileStandard()`.

**Comment by tcoulter** [comment]
Hey @axic, any chance you can post an example? This input doesn't seem to work:

```
pragma solidity ^0.14.15;

import "./Dependency.sol";

contract MyContract {

}
```

```
    var solcStandardInput = {
      language: "Solidity",
      sources: {
        "Contract.sol": {
          content: body // contract code
        }
      },
      settings: {
        outputSelection: {
          "*": {
            "*": [
              "ast",
            ]
          },
        }
      }
    };

    var output = solc.compileStandard(JSON.stringify(solcStandardInput));
```

The output is:

```
{ contracts: {},
  errors:
   [ { component: 'general',
       formattedMessage: 'Contract.sol:3:1: ParserError: Source "Dependency.sol" not found: File import callback not supported\nimport "./Dependency.sol";\n^------------------------^\n',
       message: 'Source "Dependency.sol" not found: File import callback not supported',
       severity: 'error',
       type: 'ParserError' } ],
  sources: {} }
```
