### ISSUE TITLE
Security improvement

### ISSUE THREAD

**Issue by sebs** [ethereum/solc-js#50]
[https://github.com/ethereum/solc-js/blob/master/wrapper.js#L95](https://github.com/ethereum/solc-js/blob/master/wrapper.js#L95)

This is a "neat" hack. Maybe deilver some hashes to check the files received?  Maybe this is a hint, that all this wants a different infrastructure. The whole "require from string" worries me a bit.

**Comment by chevdor** [comment]
That would be possible. The hashes would have to be delivered first into https://ethereum.github.io/solc-bin/bin/list.json

Ideally, I would suggest using sha256-256 so we could also directly get the files using IPFS.

**Comment by chriseth** [comment]
We are working on a solution here: https://github.com/ethereum/solidity/issues/628
