### ISSUE TITLE
ABI with `constant` and `payable` equal to true

### ISSUE THREAD

**Issue by yann300** [ethereum/solc-js#500]
With Solidity 0.3.3, using the `update` from `import { update } from 'solc/abi'`
produces this abi (if `constant` is originally true) - see below.
Having both `constant` and `payable` to `true` throw an error while trying to use it in ethers 5.0.

```
constant: true
inputs: []
name: "get"
outputs: [{…}]
payable: true
type: "function"
```

**Comment by chriseth** [comment]
Do you think this is an error or at least can be fixed in the wrapper?

**Comment by axic** [comment]
It is happening because of this shortcut: https://github.com/ethereum/solc-js/blob/master/abi.js#L23

Should add a condition there that it is not already marked `constant.`

**Comment by yann300** [comment]
> Do you think this is an error or at least can be fixed in the wrapper?

that can be fixed in the wrapper yes
