### ISSUE TITLE
Forbidden response from loadRemoteVersion

### ISSUE THREAD

**Issue by valmack** [ethereum/solc-js#510]
Maybe the url is outdated and binaries should be retrieved from `https://binaries.soliditylang.org/bin`

**Comment by chriseth** [comment]
Thanks for reporting - this is quite embarassing! The fix is in https://github.com/ethereum/solc-js/pull/511

**Comment by cameel** [comment]
@valmack Both domains are valid and will be supported long-term. `binaries.soliditylang.org` is recommended but mostly for cosmetic reasons (we're moving everything under `soliditylang.org`). Yeah, we should update it but things should be fine even without the change.

The HTTP 403 response just means that the file is missing. This should really be HTTP 404 but S3 won't return that unless you have permission to list bucket contents. I noticed that this is no enabled for public access so I have just updated the bucket policy. You should be getting the proper 404 errors from now on.

Can you still reproduce the problem? I think you may have passed a non-existent version to `loadRemoteVersion()` (a typo maybe?) or other than that it could have been some transient problem on Amazon's side. Both domains are attached to the same exact S3 bucket and you shouldn't even be able to access a file via one but not the other. If it wasn't you calling the function directly but rather `solc-js` then there could be a bug somewhere. One possibility that I think we can exclude is `list.json` being out of sync with available versions - we have CI checks on that and the [sync script](https://github.com/ethereum/solc-bin/blob/gh-pages/sync-s3.sh) even makes sure to update it only after new files have been successfully uploaded - which should be enough given that files are never deleted.

**Comment by valmack** [comment]
Hmm honestly don't remember exactly. i ended up writing my own script that uses` soliditylang.org` instead. probably `https://solc-bin.ethereum.org/bin/list.json` so I'm guessing your updates to the bucket policy fixed this.

**Comment by valmack** [comment]
Thanks for quick turnaround!
