### ISSUE TITLE
solc v0.8.1 published on npm does not actually contain solcjs 0.8.1

### ISSUE THREAD

**Issue by petejkim** [ethereum/solc-js#513]
```shell
$ cat node_modules/solc/package.json | grep version
  "version": "0.8.1",
$ node_modules/solc/solcjs --version
0.8.0+commit.c7dfd78e.Emscripten.clang
```

Unable to compile contracts that explicitly require 0.8.1 due to the version mismatch:

```
ParserError: Source file requires different compiler version (current compiler is 0.8.0+commit.c7dfd78e.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version
 --> contracts/Contract.sol:3:1:
  |
3 | pragma solidity 0.8.1;
```

**Comment by petejkim** [comment]
cc: @chriseth

**Comment by chriseth** [comment]
Thanks for reporting this issue! We are already aware of it ( https://github.com/ethereum/solidity/issues/10868 ), but unfortunately do not know how this happened and also cannot do anything about it until 0.8.1 is released. You can work around it by using the `loadRemoteVersion` function. It will also work with 0.8.1.
