### ISSUE TITLE
how to compile my contract with testrpc 

### ISSUE THREAD

**Issue by AsAlhashemia** [ethereum/solc-js#531]
I was create a QT project and I pass the solidity file as a string 
params.append(FileToString(CONTRACT_PATH)) ;
where CONTRACT_PATH is my solidity file  path 
when this interacts with testrpc my QT window stopped because the testrpc doesnot support eth-compilesolidity function 
so any one can show me how I can solve this issue

**Comment by chriseth** [comment]
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.
