### ISSUE TITLE
0.8.7 version mismatch

### ISSUE THREAD

**Issue by skiv71** [ethereum/solc-js#543]
My package.json specified ^0.8.6, and since the release of 0.8.7, solc and solcjs report different versions.

solc -V ---> 0.8.7

solcjs -V ---> 0.7.5

I'm using waffle and some OZ imports (which require ^0.8.0), compilation fails.

For now, I've had to nail my package.json to 0.8.6

**Comment by hrkrshnn** [comment]
The 0.8.7 version of soljs in npm got corrupted during the release and was deprecated.

Would it be possible for you to use the native version of solidity instead of solcjs from npm? https://ethereum-waffle.readthedocs.io/en/latest/compilation.html#using-native-solc

**Comment by ekpyron** [comment]
As a workaround, it might also help to run ``node downloadCurrentVersion.js`` (should be contained in the same directory as ``solcjs``).

**Comment by hrkrshnn** [comment]
@skiv71 Could you please follow up if the suggestions indeed fixed the issue?

**Comment by ekpyron** [comment]
I think after a year, it's fair to close this for inactivity.
