### ISSUE TITLE
integrate with truffle

### ISSUE THREAD

**Issue by yhjhoo** [ethereum/solc-js#550]
if there a way to use solc-js in truffle? any example?

**Comment by cameel** [comment]
Truffle already [uses solc-js](https://github.com/trufflesuite/truffle/blob/v5.4.10/packages/compile-solidity/package.json#L35) (note that the npm package is called `solc`), so I'm not sure what you mean by "integrating" it.

In any case, this is a bug tracker and this does not seem to be a bug report or a feature request. The [#solidity](https://gitter.im/ethereum/solidity-dev) channel on Gitter is a much better place for support questions.
