### ISSUE TITLE
UNMET PEER DEPENDENCY solc@^0.3.5

### ISSUE THREAD

**Issue by zhouyasong** [ethereum/solc-js#58]
hello!
I recently in buliding the ethereum development environment.Everything goes well with the early,include truffle and testrpc.
But when I install solc.I met a big trouble.

sudo npm install -g solc solc-cli --save-dev
├── UNMET PEER DEPENDENCY solc@^0.3.5
└── solc-cli@0.3.0 
npm WARN solc-cli@0.3.0 requires a peer of solc@^0.3.5 but none was installed.

I try install solc first,but the solc virsion is 

└─┬ solc@0.4.2 
  ├── memorystream@0.3.1 
  ├── require-from-string@1.2.0 
  └─┬ yargs@4.8.1 
    ├─┬ cliui@3.2.0 
    │ ├─┬ strip-ansi@3.0.1 
    │ │ └── ansi-regex@2.0.0 
    │ └── wrap-ansi@2.0.0 
    ├── decamelize@1.2.0 
    ├── get-caller-file@1.0.2 
    ├── lodash.assign@4.2.0 
    ├─┬ os-locale@1.4.0 
    │ └─┬ lcid@1.0.0 
    │   └── invert-kv@1.0.0 
    ├─┬ read-pkg-up@1.0.1 
    │ ├─┬ find-up@1.1.2 
    │ │ ├── path-exists@2.1.0 
    │ │ └─┬ pinkie-promise@2.0.1 
    │ │   └── pinkie@2.0.4 
    │ └─┬ read-pkg@1.1.0 
    │   ├─┬ load-json-file@1.1.0 
    │   │ ├── graceful-fs@4.1.8 
    │   │ ├─┬ parse-json@2.2.0 
    │   │ │ └─┬ error-ex@1.3.0 
    │   │ │   └── is-arrayish@0.2.1 
    │   │ ├── pify@2.3.0 
    │   │ └─┬ strip-bom@2.0.0 
    │   │   └── is-utf8@0.2.1 
    │   ├─┬ normalize-package-data@2.3.5 
    │   │ ├── hosted-git-info@2.1.5 
    │   │ ├─┬ is-builtin-module@1.0.0 
    │   │ │ └── builtin-modules@1.1.1 
    │   │ ├── semver@5.3.0 
    │   │ └─┬ validate-npm-package-license@3.0.1 
    │   │   ├─┬ spdx-correct@1.0.2 
    │   │   │ └── spdx-license-ids@1.2.2 
    │   │   └── spdx-expression-parse@1.0.3 
    │   └── path-type@1.1.0 
    ├── require-directory@2.1.1 
    ├── require-main-filename@1.0.1 
    ├── set-blocking@2.0.0 
    ├─┬ string-width@1.0.2 
    │ ├─┬ code-point-at@1.0.0 
    │ │ └── number-is-nan@1.0.0 
    │ └── is-fullwidth-code-point@1.0.0 
    ├── which-module@1.0.0 
    ├── window-size@0.2.0 
    ├── y18n@3.2.1 
    └─┬ yargs-parser@2.4.1 
      └── camelcase@3.0.0 

The solc-cli need solc@^0.3.5.

thanks for the help!

**Comment by chriseth** [comment]
This rather looks like a bug in solc-cli, it requires the old version 0.3 while solidity itself is now at 0.4.

Note that solc-js now provides a commandline interface itself, called `solcjs`, so you could just use
`npm install -g solcjs`. Please reopen if this does not help.
