### ISSUE TITLE
how does address.sol and safemath.sol return the same bytecode?

### ISSUE THREAD

**Issue by eladalkabets2603** [ethereum/solc-js#582]
[Address.txt](https://github.com/ethereum/solc-js/files/7890686/Address.txt)
[SafeMath.txt](https://github.com/ethereum/solc-js/files/7890695/SafeMath.txt)
(.sol extension isnt supported)
i recently used your solc,js in one of my project , where i copied sol files using chain explorers devided them into sub contract  , added the imports and compiled them to get the byte code.
while testing the code i ran into something odd (in my opinion)
both safemath.sol and address.sol (from the sushi token on 0x6B3595068778DD592e39A122f4f5a5cF09C90fE2 ethereum mainnet)
 how are both of these files return the same byte code? is it because they are a pert of the same project (if so what is the point of getting the bytecode of the imported contract)

ps.
the same happens on remix d

**Comment by cameel** [comment]
This is not a bug. Both files define libraries with only internal and private functions. These cannot be called from the outside so they don't produce any bytecode until you add some external or public function that calls them.

These seem to come from OpenZeppelin. Please note that they are not meant to be deployed on their own so even the bytecode they do produce is not meant to be put on the chain. You use them by calling their internal functions from other functions in your contract.
