### ISSUE TITLE
Ensure that tests work even if `/tmp` is not accessible

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#588]
`test/compiler.js` assumes that `/tmp` is always accessible. We should use a function that creates a temporary dir instead.

_Originally posted by @cameel in https://github.com/ethereum/solc-js/pull/566#discussion_r762097623_

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by cameel** [comment]
Sure. Feel free to submit a PR!
