### ISSUE TITLE
Please raise compiler memory limit.. large "var (tuples)" during inter-contract calls now overflow :-(

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/solc-js#60]
In version solc 3.7> I use to be able to have large var tuple instantiation without causing a memory overflow.

Such as:
```
BoardRoom board = BoardRoom(msg.sender);
var (name, destination, proxy, value, hash, executed, debatePeriod, created) = board.proposals(_proposalID);
```

Now things like this are causing massive memory overflow. I remember we can just raise the memory limit somewhere in the compiler. Can we raise this again, I had asked before and during v3 and we raised it. Looks like we set it back again.

Otherwise I have to add a crap ton of getters to my contract... not looking forward to it =(

Thanks yall.

**Comment by axic** [comment]
@SilentCicero can you check this with the command line compiler (and not the Emscripten version)?

**Comment by chriseth** [comment]
@SilentCicero There is no such thing as a "memory limit" than can be raised. The problem you encounter is a combination of the limitaiton of the EVM to only provide access to the 16 topmost stack elements and the lack of a automatic routine in the compiler to move stack elements to memory. This story will provide a workaround by introducing structs that you can return: https://github.com/ethereum/solidity/issues/595
