### ISSUE TITLE
Why is `solc.lowlevel.compileCallback` `null` on solc 0.8.12?

### ISSUE THREAD

**Issue by Y-Zeus** [ethereum/solc-js#610]
```javascript
const solc = require('solc');

if (typeof solc.lowlevel.compileSingle != 'function') {
		console.log('Low-level compileSingle interface not implemented by this compiler version.');
}
```
result:
```
TypeError: solc.lowlevel.compileCallback is not a function
```

solc version 0.8.12
why?

**Comment by cameel** [comment]
These low-level functions were superseded by `compile()` and are no longer needed (https://github.com/ethereum/solidity/issues/3452). They were removed from the binary in 0.5.0 (https://github.com/ethereum/solidity/pull/5105).

The only reason they're still present under `lowlevel` is that solc-js is meant to support all compiler binaries, including the ones older than 0.5.0. The check will succeed if you use it with such a binary.

But you have a point in that it's not explained in the README. We should make it clearer.

**Comment by Y-Zeus** [comment]
> 这些低级功能已被取代`compile()`并且不再需要（[ethereum/solidity#3452](https://github.com/ethereum/solidity/issues/3452)）。它们已从 0.5.0 ( [ethereum/solidity#5105](https://github.com/ethereum/solidity/pull/5105) ) 中的二进制文件中删除。
> 
> 它们仍然存在的唯一原因`lowlevel`是 solc-js 旨在支持所有编译器二进制文件，包括早于 0.5.0 的那些。如果您将其与此类二进制文件一起使用，则检查将成功。对于较新的，它们是`null`.
> 
> 但是你有一点，它没有在自述文件中解释。我们应该说得更清楚。

**Comment by Y-Zeus** [comment]
thanks

**Comment by cameel** [comment]
I'll keep this open. I think we should add something about it to the README.

**Comment by r0qs** [comment]
Fixed by https://github.com/ethereum/solc-js/pull/658.
