### ISSUE TITLE
Unable to retrieve AST after compilation

### ISSUE THREAD

**Issue by MJYoung114** [ethereum/solc-js#618]
Hi team, 

Is there a way to retrieve the AST from the compiled output?

Using the below or any variation of the below with 

`outputSelection: {
      '*': {
        '*': ['ast']
      }` 

does not return any ast.

```var solc = require('solc');

var input = {
  language: 'Solidity',
  sources: {
    'test.sol': {
      content: 'import "lib.sol"; contract C { function f() public { L.f(); } }'
    }
  },
  settings: {
    outputSelection: {
      '*': {
        '*': ['ast']
      }
    }
  }
};

function findImports(path) {
  if (path === 'lib.sol')
    return {
      contents:
        'library L { function f() internal returns (uint) { return 7; } }'
    };
  else return { error: 'File not found' };
}

// New syntax (supported from 0.5.12, mandatory from 0.6.0)
var output = JSON.parse(
  solc.compile(JSON.stringify(input), { import: findImports })
);

// `output` here contains the JSON output as specified in the documentation
for (var contractName in output.contracts['test.sol']) {
  console.log(
    contractName +
      ': ' +
      output.contracts['test.sol'][contractName].evm.bytecode.object
  );
}`

**Comment by cameel** [comment]
See output description in [Compiler Input and Output JSON Description](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description):
> ```
> // File level (needs empty string as contract name):
> //   ast - AST of all source files
> ```

Also, this is a bug tracker for the project, not a place to ask support questions. Please use the [#solidity](https://gitter.im/ethereum/solidity) channel or Ethereum Stack Exchange unless you think you actually found a bug in solc-js or you have a feature request.
