### ISSUE TITLE
Solc compile does not work

### ISSUE THREAD

**Issue by Hyperienn** [ethereum/solc-js#636]
Hey guys,
I am learning ethers. js and having an issue with solc-js. I cannot compile my code even though I installed it through npm. Here' s my error.
```
solcjs --bin --include-path node_modules/ --base-path . SimpleStorage.sol
>> 
solcjs : The term 'solcjs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the p
ath is correct and try again.
At line:1 char:1
+ solcjs --bin --include-path node_modules/ --base-path . SimpleStorage ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (solcjs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

And this is the content in package.json
![solcjs](https://user-images.githubusercontent.com/38370087/174425927-b8c459fe-fe18-4181-b190-7763df77bd59.png)

**Comment by cameel** [comment]
Not a bug. That's just not how you call a command from a npm package. It's either `npx solcjs <options>` (if you installed it via npm) or `./solc.js` (if you cloned the repo). But for command-line use I'd recommend getting a binary for your platform from [solc-bin](https://github.com/ethereum/solc-bin/). The CLI interface of the `solcjs` script is very limited.
