### ISSUE TITLE
ether version  is not showing

### ISSUE THREAD

**Issue by crack4it** [ethereum/solc-js#637]
Hi,
when i type "yarn add ethers" in my terminal 
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning No license field
success Saved 16 new dependencies.
info Direct dependencies
└─ ethers@5.6.9
info All dependencies
├─ @ethersproject/abi@5.6.4
├─ @ethersproject/contracts@5.6.2
├─ @ethersproject/json-wallets@5.6.1
├─ @ethersproject/providers@5.6.8
├─ @ethersproject/solidity@5.6.1
├─ @ethersproject/units@5.6.1
├─ @ethersproject/wallet@5.6.2
├─ aes-js@3.0.0
├─ bech32@1.1.4
├─ brorand@1.1.0
├─ elliptic@6.5.4
├─ ethers@5.6.9
├─ hmac-drbg@1.0.1
├─ minimalistic-assert@1.0.1
├─ scrypt-js@3.0.1
└─ ws@7.4.6
Done in 38.82s.
these all things happend but the version is not shown in package.json file
https://youtu.be/gyMwXuJrbJQ?t=25257 (he did it here)

**Comment by axic** [comment]
This is the wrong repository, please contact https://github.com/ethers-io.
