### ISSUE TITLE
On deploy.js  i get this error reason: 'could not detect network',

### ISSUE THREAD

**Issue by ratalviper** [ethereum/solc-js#644]
While running node deploy.js i get this error. Please help... (tutorial video time 07:07:15)
`rpc-provider.js:48:23)
    at Object.throw (/home/ratalviper/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/ratalviper/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'`

 
![Capture](https://user-images.githubusercontent.com/87262417/179418840-5d658018-096f-4377-a11a-540a61b96ed9.PNG)

`

`

**Comment by ratalviper** [comment]
Ok finally solved this error had to change server to WSL Linux in Ganache so it worked. ScreenShot attached if anyone faces same issue :)


![Capture](https://user-images.githubusercontent.com/87262417/179419529-ffa0a3ee-05d9-4acc-9060-e569f62dae86.PNG)

**Comment by cameel** [comment]
Closing, since, apart from not being a bug, it's also unrelated to solc-js. Note that the error message comes from [ethers.js](https://docs.ethers.io). The compiler only compiles contracts. It does not communicate with an Ethereum node.
