### ISSUE TITLE
Troubles witch yarn solc

### ISSUE THREAD

**Issue by Xardesso** [ethereum/solc-js#660]
something goes wrong when i paste code in terminal and i dont know what i should do.Its my firs github post 
code:
yarn solcjs --bin --abi --incl ude - path node_modules / --base - path . -o . SimpleStorage.sol
thx for help
![image](https://user-images.githubusercontent.com/112291196/191512493-d5cdb81b-c6c4-497b-9f88-798c80c3fc84.png)

**Comment by cameel** [comment]
You have stray spaces in your command. It should probably look like this:
```bash
yarn solcjs --bin --abi --include-path node_modules/ --base-path . -o . SimpleStorage.sol
```

But this is not the right places for asking support questions. Please drop by at the [#solidity](https://app.element.io/#/room/#ethereum_solidity:gitter.im) channel instead.
