### ISSUE TITLE
Contract Source Files as inputs for compilations

### ISSUE THREAD

**Issue by nissshh** [ethereum/solc-js#71]
I am a newbee on ethereum and trying to evaluate this package for automated-deployment , My idea is to provide source 'files' (not just strings) to the solc-js and then somehow use this as  a deployment services. Its hard to put string directly in the definitions where the actual contract code lies in different files.

**Comment by nissshh** [comment]
I saw this esample that could be of help
https://github.com/ethereum/solc-js/blob/master/test/determinism.js

**Comment by axic** [comment]
You can use the frontend called `solcjs` or the library directly. Please reopen if something is not clear.
