### ISSUE TITLE
0.8.23 npm release won't install on Windows due to a stray dependency

### ISSUE THREAD

**Issue by Janther** [ethereum/solc-js#715]
The last release has a dependency `"n": "^9.2.0"` and is blocking the installation of this package on windows machines since it [does not support](https://github.com/tj/n#supported-platforms) that.

Oddly enough there is no mention of this package in the repo.

<img width="804" alt="Screen Shot 2023-11-09 at 5 08 40 PM" src="https://github.com/ethereum/solc-js/assets/1022054/2a10fff5-bb42-4b0a-a662-8a1042de5c77">

<img width="265" alt="Screen Shot 2023-11-09 at 5 09 00 PM" src="https://github.com/ethereum/solc-js/assets/1022054/2a3beb14-ddd0-481b-87f8-12179aefc8b9">

**Comment by Janther** [comment]
if I look at the [release on GitHub](https://github.com/ethereum/solc-js/releases/tag/v0.8.23), it doesn't have that dependency either but it does when I look at the [npm package](https://www.npmjs.com/package/solc)

**Comment by Janther** [comment]
I reverted the bump on `solc@0.8.23` so we can safely publish a version that runs on all machines

**Comment by cameel** [comment]
Yes, that dependency should not be there. It must have been introduced when the release package was being built.

Unfortunately npm does not allow reuploading packages so fixing this will require a new release. For now downgrading to 0.8.22 sounds like a good workaround.

**Comment by matheusaaguiar** [comment]
Hi @Janther , unfortunately this dependency was accidentally inserted and although unrelated and harmless, it doesn't work in Windows and thus create the problem you reported.
We have released [`0.8.23-fixed`](https://www.npmjs.com/package/solc/v/0.8.23-fixed) to address that until we the next release.
