### ISSUE TITLE
Error: Cannot find module 'ws' from '/home/nick/github/wafr/node_modules/solc' while browserify

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/solc-js#72]
```
Error: Cannot find module 'ws' from '/home/nick/github/wafr/node_modules/solc'
    at /home/nick/github/wafr/node_modules/resolve/lib/async.js:46:17
    at process (/home/nick/github/wafr/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/nick/github/wafr/node_modules/resolve/lib/async.js:188:17)
    at load (/home/nick/github/wafr/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/nick/github/wafr/node_modules/resolve/lib/async.js:92:31)
    at /home/nick/github/wafr/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I should be able to browserify a module that depends on and `require`s `solc`. But I keep getting this error, where the `ws` package is not required.

Should we install this as a dependency and include it in the package.json? How should I proceed?

**Comment by chriseth** [comment]
We are successfully browserifying browser-solidity which also `require`s solc-js, although it only loads `solc/wrapper` - which is probably what you should also do.

**Comment by SilentCicero** [comment]
what about the sol-json? @chriseth -- can you provide the browserify CLI commands/code?

**Comment by chriseth** [comment]
Note that we are not browserifying the compiler itself, this will crash browserify - we load that on the fly at runtime. Here is the package.json: https://github.com/ethereum/browser-solidity/blob/master/package.json

**Comment by axic** [comment]
I'm not sure if this issue is still relevant. Please reopen if it is.
