### ISSUE TITLE
findImports fallback on webWorkers not working

### ISSUE THREAD

**Issue by ashwwwin** [ethereum/solc-js#722]
Hey, I'm to trying to use the import fallback with web workers as follows but can't get it to work (the console.log doesn't get called either).

 It compiles without issue if there are no imports or if compiling multiple contracts, I am using this method in order to get the main contract and imported contracts into a single compiled abi + bytecode.

My findImports function:
```
function getImport(path: any) {
      console.log('getImport called for', path);
      return {
        contents:
          "library L { function f() internal returns (uint) { return 7; } }",
      };
    }
```

Compilation:
```
 const compile = soljson.cwrap("solidity_compile", "string", [
        "string",
        "number",
        "function",
      ]);

const output = JSON.parse(compile(data.input, { import: getImport }));
```

Any leads would be much appreciated.

**Comment by dreadheadsic** [comment]
You're wrapping the `solidity_compile` C function so your callback has to be second argument: 
`compile(data.input, getImport)`

**Comment by ashwwwin** [comment]
> You're wrapping the `solidity_compile` C function so your callback has to be second argument: `compile(data.input, getImport)`

@dreadheadsic, thank you for the response - I tried this and it did not work.

 It does seem like the C function, does not support compilations with imports - haven't been able to get it work (I am not entirely sure). This has been a huge pain point, if you have any leads would appreciate.

**Comment by dreadheadsic** [comment]
Use `'solc/wrapper'` to wrap your solidity worker
```
import wrapper from 'solc/wrapper';

self.importScripts(`https://binaries.soliditylang.org/wasm/${data.version}`);

const compiler = wrap(self);
```
then you can do
```
const result = await wrappedCompiler.compile(decodedInput, {
    import: getImports,
});
const data = JSON.parse(result);
```

**Comment by ashwwwin** [comment]
> ```
> const compiler = wrap(self);
> ```

For this line, do you mean const `compiler = wrapper(self);`?

**Comment by dreadheadsic** [comment]
Yes

**Comment by ashwwwin** [comment]
Finally got it to work! Thank you - turns out my real struggle was with the webpack stuff.

**Comment by mehtavishwa30** [comment]
Closing this as the issue seems to have been resolved as confirmed by @ashwwwin.
