### ISSUE TITLE
Question: Is the generated ABI in written order?

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/solc-js#73]
If I have contract:

```
contract MyContract {

    function A() {}

    funciton B() {}
}
```

In the contract outputs, will method A always be in front of method B in the ABI array?

ABI:
```
[{name: "A" ...}, {name: "B" ...} ...]
```

Or is there no guarantee or requirement for this by a Ethereum contract compiler?

**Comment by axic** [comment]
The order depends on the JSON library which way it (de)serialises

**Comment by axic** [comment]
Please open this as an issue on https://github.com/ethereum/solidity if the answer is not comprehensive.
