### ISSUE TITLE
Web3ContractError: code couldn't be stored

### ISSUE THREAD

**Issue by Jagadeeshftw** [ethereum/solc-js#736]
$ npm run test

> smartcontract@1.0.0 test
> mocha

  Inbox
eth_accounts
eth_getBlockByNumber
eth_blockNumber
eth_sendTransaction

  Transaction: 0x4e43bcb26ad43cc4e3825bc992d9d3c1443fbfddb7396ed99ae79fb5926af9ec
  Contract created: 0x4882b07cdd9fddabceb4e6a4de4ec53c9d708014
  Gas usage: 1000000
  Block number: 1
  Block time: Thu Apr 11 2024 10:14:44 GMT+0530 (India Standard Time)
  Runtime error: invalid opcode

eth_getTransactionReceipt
eth_blockNumber
    1) "before each" hook for "deploys a contract"

  0 passing (287ms)
  1 failing

  1) "before each" hook for "deploys a contract":
     Web3ContractError: code couldn't be stored
      at Object.transactionResolver (node_modules\web3-eth-contract\lib\commonjs\contract.js:741:27)
      at SendTxHelper.<anonymous> (node_modules\web3-eth\lib\commonjs\utils\send_tx_helper.js:155:84)
      at Generator.next (<anonymous>)
      at C:\Users\JagadeeshB\practice\smartContract\node_modules\web3-eth\lib\commonjs\utils\send_tx_helper.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules\web3-eth\lib\commonjs\utils\send_tx_helper.js:4:12)
      at SendTxHelper.handleResolve (node_modules\web3-eth\lib\commonjs\utils\send_tx_helper.js:153:16)
      at C:\Users\JagadeeshB\practice\smartContract\node_modules\web3-eth\lib\commonjs\rpc_method_wrappers.js:374:48
      at Generator.next (<anonymous>)
      at fulfilled (node_modules\web3-eth\lib\commonjs\rpc_method_wrappers.js:21:58)

my solidity file:

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.19;

contract Inbox {
    string public message;
    
    constructor(string memory initialMessage) {
        message = initialMessage;
    }
    
    function setMessage(string memory newMessage) public {
        message = newMessage;
    }
}
package.json:

{
  "name": "smartcontract",
  "version": "1.0.0",
  "description": "Aims to create a simple smart Contract",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@truffle/hdwallet-provider": "^2.1.15",
    "ganache": "^7.9.2",
    "solc": "^0.8.25",
    "web3": "^4.7.0"
  },
  "devDependencies": {
    "mocha": "^10.3.0"
  }
}
but when i install and test with 0.8.9 version, that time i didnt face any issues

**Comment by mehtavishwa30** [comment]
Hey @Jagadeeshftw! Please note that this is an issue that arises as a result of you using solc-js with Truffle/Ganache which does not support Cancun. Hence, I will be closing this issue.
