### ISSUE TITLE
Feature Request: allow for input of pre-compiled bytecode

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/solc-js#80]
Right now the `solc` compiler can only intake the sources of solidity files/source maps. But when I'm compiling more than say, 15 contracts (which I do often, as many of us use the EVM/solc as a testing environment). The compile time takes forever, sometimes up to 10+ minutes depending on the source. Many of the contracts I'm compiling have already been compiled (and have not changed). Often times, I may only be changing one or two at most. So I'd like to request a bytecode input feature (if something like this is possible and doable).

Usage:
```js
var solc = require('solc');
var input = {
    'lib.sol': 'library L { function f() returns (uint) { return 7; } }',
    'cont.sol': 'import "lib.sol"; contract x { function g() { L.f(); } }',
};
var bytecode = {
    'cont.sol': '0x00..',
};
var output = solc.compile({ sources: input, bytecode: bytecode }, 1);
```

This way, if the bytecode is presented for a specific contract, then it won't recompile the source, instead it will just use the source provided.

Optimizations like this allow us to have a faster environment to develop large Solidity applications. This way,  the build environment can optimize compile time by presenting bytecode that often times does not change.

Thoughts?

One con/Fix:
 - what if the bytecode is old and the contract has actually changed, but the build environment improperly handled the change, and did not recompile code properly.
    Potential Fix: instead of the bytecode map being "contract_name": "bytecode", it could be: "keccak256(contract_code)": "bytecode". This way, the map will only map to that contracts bytecode and nothing else. This would avoid a situation where bytecode is presented for an old contract code.

**Comment by axic** [comment]
This is tracked in https://github.com/ethereum/solidity/issues/1540
