### ISSUE TITLE
`solc` breaks mocha test runner.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solc-js#84]
Repro case here: https://github.com/MicahZoltu/mocha-test/

Run either with `docker build -t mocha-test . && docker run --rm mocha-test` or with `npm install && node_modules/.bin/mocha`.  Notice that the test runner crashes.

Comment out the line here https://github.com/MicahZoltu/mocha-test/blob/master/test/example.js#L2-L3 and then notice that the test runner does not crash.

Prime suspect is https://github.com/ethereum/solc-js/blob/master/solcjs#L8, though replacing the `require("solc")` line with that does not cause the problem to persist.  I have been unable to narrow down the problem past `solc`, though the test runner crash output suggests that `solc` is to blame.

**Comment by MicahZoltu** [comment]
A bit more research suggests the problem is actually with a listener that `solc` adds, not the fact that it removes all listeners.  I have updated the repro case to show how to work around this problem temporarily.

Opinion
====
It is bad form for a library to call `process.removeAllListeners`.  This has global effect and will undo any listeners that were added before this library is included.  I suspect that the crashing is simply a bug in the listener that `solc` adds and that actually bothers me far less since bugs happen.  The removal of all listeners when the user calls `require('solc')` however is a more fundamental problem.

**Comment by axic** [comment]
> with a listener that solc adds

Actually `emscripten` is adding the listener and solc only tries to counteract it.

**Comment by MicahZoltu** [comment]
In that case, it appears that the counteracting isn't working.  :)  If you have a script that just does `require('solc')` and nothing else, you will find that the set of listeners before that call is the empty set and the set of listeners after that call is a set of 1.

**Comment by MicahZoltu** [comment]
I would be happy to submit a PR that does a more targeted removal of the `unhandledException` listener that is added, but I'm not sure where to put it so that it will work.  As I mentioned above, the current location of `process.removeAllListeners()` isn't actually working.  Perhaps there was some kind of restructuring that caused the desired behavior to break?  Unfortunately, this project isn't setup the way I am used to so I'm not sure how the `emscripten` is getting included?

**Comment by axic** [comment]
The Solidity compiler, written in C++, is compiled using Emscripten to Javascript. That output created by Emscripten includes the listener.

**Comment by tcoulter** [comment]
@MicahZoltu You don't have to call `process.removeAllListeners()` to workaround the issue. You can remove the last listener directly after importing solc. Here's how Truffle does it. https://github.com/trufflesuite/truffle-compile/blob/master/index.js#L4

Aside: I keep the listener for the very rare case it's still needed, and I pop it on when using solc then immediately pop it off again. I probably don't have to do this, and will consider removing it.

**Comment by MicahZoltu** [comment]
I'm a little uncomfortable with relying on the internal mechanism by which `solc` is adding the listener, particularly depending on the added listener being to the end and depending on `solc` only adding a single listener.  That being said, it is a tad less ugly than caching the existing listener set and then clearing/re-adding them all after.
