### ISSUE TITLE
Insignificant newline changes output of solc.compile

### ISSUE THREAD

**Issue by willnwhite** [ethereum/solc-js#88]
A newline (`\n`) at the end of a contract's source code causes the output bytecode to be different to the same contract without the newline. So, for example, if you copy and paste a contract into a string to be compiled, the result may be different to reading the source code into a string from file.

**Comment by axic** [comment]
This is due to the verification metadata. The bytecode contains a hash of the metadata, which in turn contains hashes of the sources used.

More explanation here: http://solidity.readthedocs.io/en/develop/miscellaneous.html#contract-metadata

**Comment by chriseth** [comment]
We could strip whitespace at the beginning and end of sources, but I think if we start doing this, we will never find an end to similar problems.
