### ISSUE TITLE
Compiles under 0.4.4, "breaks" in 0.4.9

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solc-js#89]
https://gist.github.com/anonymous/888b4c16a560f8799ac92e865a09e10c

In 4.9, the returned binary for GiftableToken is blank

For context:
https://github.com/ethereum/browser-solidity/issues/474

**Comment by axic** [comment]
This is still not the right place, it should be reported at http://github.com/ethereum/solidity 😉

**Comment by aakilfernandes** [comment]
One day I'll get there! Turns out you were right the first time. It was an abstraction issue, not a solidity or remix issue. Thanks as always!
