### ISSUE TITLE
Why doesn't this package include a cli?

### ISSUE THREAD

**Issue by raineorshine** [ethereum/solc-js#9]
I was expecting I could `npm install -g solc` and have `solc` in my path. That was the impression I got from https://solidity.readthedocs.io/en/latest/installing-solidity.html:

> ## NPM / node.js
> This is probably the most portable and most convenient way to install Solidity locally.
> 
> A platform-independent JavaScript library is provided by compiling the C++ source into JavaScript using > Emscripten for browser-solidity and there is also an NPM package available.
> 
> To install it, simply use
> 
>     npm install solc

I guess I just install the [binaries](https://github.com/ethereum/webthree-umbrella/releases) instead?

**Comment by raineorshine** [comment]
Or perhaps I install it with [these instructions](https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial) (brew on Mac):

```
brew install cpp-ethereum
brew linkapps cpp-ethereum
which solc
```

**Comment by axic** [comment]
I think the documentation is misleading.  In theory a cli could be written on top of solc-js, but it would be limited in options compared to the C++ solc cli.

**Comment by raineorshine** [comment]
Okay, thanks. Was a bit confusing.

Installing cpp-ethereum with brew worked.

**Comment by redsquirrel** [comment]
@raineorshine I was confused about this too when I got started. Seems like there's an opportunity to clarify things on the npm/solc page.

**Comment by chriseth** [comment]
Someone should extend the package :-)

**Comment by InsidersByte** [comment]
@raineorshine @redsquirrel @chriseth @axic I created a simple cli https://github.com/InsidersByte/solc-cli

**Comment by raineorshine** [comment]
@InsidersByte Great work!

I do think it may be less confusing for people if cli functionality was built into the `solc` package.

**Comment by redsquirrel** [comment]
See #27

**Comment by InsidersByte** [comment]
ha, I didn't realise there was an open pull request when I wrote it. Looks like I wrote it the day after it was created.

**Comment by redsquirrel** [comment]
@InsidersByte Great minds think alike... at the same time! 😄
