### ISSUE TITLE
Contract name starts with colon in compiled output

### ISSUE THREAD

**Issue by ygnr** [ethereum/solc-js#91]
`solc.compile(exampleContract)` returns the following. It would be good to remove colon before contract name.
```
{
  "contracts": {
     ":NameOfContract": {...}
  }
} 
```

**Comment by chriseth** [comment]
To make contract references unambiguous in the output, newer compiler versions prefix every contract with `<filename>:`. This will be further expanded in the next version where a proper json object will be returned, so please stay tuned for a "fix".

**Comment by axic** [comment]
I close this as it is not a "bug", just how the compiler works.
