### ISSUE TITLE
Extend testing infrastructure

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#96]
Should run tests using different compiler versions.

**Comment by axic** [comment]
It would be the best running it with every single release.

**Comment by watilde** [comment]
`solidity` seems to have 38 tags already.
> https://github.com/ethereum/solidity/releases

How about testing for the last 3 releases on ci?

**Comment by axic** [comment]
It should test for this list: https://github.com/ethereum/solc-bin/blob/gh-pages/bin/list.json#L4435-L4471
